#pragma once

// should be in cpp
#include <model/studio/studio.h>
#include <model/studio/studio_r1.h>
#include <model/studio/studio_r2.h>
#include <model/studio/studio_r5.h>
//#include <model/studio/optimize.h>

inline char* AllocStudioString(const char* const src, const size_t MAX_SIZE = MAX_PATH_SOURCE)
{
	return AllocString(src, MAX_SIZE);
}

template<typename T>
inline T* AllocStudioBuffer(const T* const src, const size_t count)
{
	return AllocBuffer(src, count);
}


class IModel;

//
// Model Source File
//

struct IModelSourceVersion_t
{
	IModelSourceVersion_t(const char* const str) : major(-1), minor(-1)
	{
		const int result = sscanf_s(str, "major %i minor %i", &major, &minor);

		assertm(result, "invalid format");
	}

	int major;
	int minor;
};

enum class IModelSourceType_t : uint32_t
{
	SOURCE_STUDIO = 0,
	SOURCE_QC = 1,

	SOURCE_FAILED, // failed to parse source
	SOURCE_INVALID,
};

struct studiosource_t
{
	//studiosource_t(std::filesystem::path filePathIn, char* pMDLIn, char* pVTXIn, char* pVVDIn, char* pVVCIn, char* pVVWIn, char* pPHYIn, const int checksumIn, const int versionIn, const int versionPakIn);
	studiosource_t(const r1::studiohdr_t* const pHdr);
	studiosource_t(const r2::studiohdr_t* const pHdr);
	studiosource_t(const r5::studiohdr_t* const pHdr, const IModelSourceVersion_t srcVer);
	~studiosource_t();

	// file data
	int id;
	int checksum;		// for checking against files
	int version;		// version of the original studio mdl, unneeded?
	int version_minor;	// in rpak, negative if not pak supported
};

union IModelSource_t {
	studiosource_t* pStudioSource;
	void* pQCSource;
	void* pInvalid;
};

typedef uint64_t IModelSourceFlags_t;

// see STUDIOHDR_FLAGS for descriptions
enum eIModelFlags : IModelSourceFlags_t
{
	IMODELFLAGS_NONE,

	IMODEL_FLAG_AUTOGENERATED_HITBOX	= 0x1,
	IMODEL_FLAG_USES_ENV_CUBEMAP		= 0x2,
	IMODEL_FLAG_FORCE_OPAQUE			= 0x4,
	IMODEL_FLAG_TRANSLUCENT_TWOPASS		= 0x8,
	IMODEL_FLAG_STATIC_PROP				= 0x10,
	IMODEL_FLAG_USES_FB_TEXTURE		    = 0x20,
	IMODEL_FLAG_HASSHADOWLOD			= 0x40,
	IMODEL_FLAG_USES_BUMPMAPPING		= 0x80,
	IMODEL_FLAG_USE_SHADOWLOD_MATERIALS	= 0x100,
	IMODEL_FLAG_OBSOLETE				= 0x200,
	IMODEL_FLAG_UNUSED					= 0x400,
	IMODEL_FLAG_NO_FORCED_FADE			= 0x800,
	IMODEL_FLAG_FORCE_PHONEME_CROSSFADE	= 0x1000,
	IMODEL_FLAG_CONSTANT_DIRECTIONAL_LIGHT_DOT = 0x2000,
	IMODEL_FLAG_FLEXES_CONVERTED			= 0x4000,
	IMODEL_FLAG_BUILT_IN_PREVIEW_MODE		= 0x8000,
	IMODEL_FLAG_AMBIENT_BOOST				= 0x10000,
	IMODEL_FLAG_DO_NOT_CAST_SHADOWS			= 0x20000,
	IMODEL_FLAG_CAST_TEXTURE_SHADOWS		= 0x40000,
	IMODEL_FLAG_SUBDIVISION_SURFACE			= 0x80000,
	IMODEL_FLAG_NO_ANIM_EVENTS				= 0x100000,
	IMODEL_FLAG_VERT_ANIM_FIXED_POINT_SCALE	= 0x200000,
	IMODEL_FLAG_PS3_EDGE_FORMAT				= 0x400000, // portal 2 supported ps3 so it should have this flag
	IMODEL_FLAG_UNK_800000						= 0x800000,
	IMODEL_FLAG_USES_VERTEX_COLOR				= 0x1000000,
	IMODEL_FLAG_USES_UV2						= 0x2000000,
	IMODEL_FLAG_UNK_4000000						= 0x4000000,
	IMODEL_FLAG_USES_UV3						= 0x8000000,
	IMODEL_FLAG_UNK_10000000					= 0x10000000,

	// flags that have been adjusted from their original bit
	IMODEL_FLAG_USES_EXTRA_BONE_WEIGHTS			= 0x100000000, // originally 0x4000
	IMODEL_FLAG_UNK_8							= 0x200000000, // originally 0x8
	IMODEL_FLAG_UNK_400							= 0x400000000, // originally 0x400
	IMODEL_FLAG_UNK_2000						= 0x800000000, // originally 0x2000
};


//
// Model IK Data
//

class IModelIKLock
{
public:
	IModelIKLock() = default;
	IModelIKLock(const r1::mstudioiklock_t* const pIKLock) : chain(pIKLock->chain), flPosWeight(pIKLock->flPosWeight), flLocalQWeight(pIKLock->flLocalQWeight), flags(pIKLock->flags) {}
	IModelIKLock(const r2::mstudioiklock_t* const pIKLock) : chain(pIKLock->chain), flPosWeight(pIKLock->flPosWeight), flLocalQWeight(pIKLock->flLocalQWeight), flags(pIKLock->flags) {}

	inline const uint32_t GetChain() const { return chain; }
	inline const float GetPosWeight() const { return flPosWeight; }
	inline const float GetLocalQWeight() const { return flLocalQWeight; }

private:
	uint32_t chain;
	float flPosWeight;
	float flLocalQWeight;
	int flags;
}; 

class IModelIKLink
{
public:
	IModelIKLink() = default;
	IModelIKLink(const r1::mstudioiklink_t* const pIKLink) : bone(pIKLink->bone), kneeDir(pIKLink->kneeDir) {}
	IModelIKLink(const r2::mstudioiklink_t* const pIKLink) : bone(pIKLink->bone), kneeDir(pIKLink->kneeDir) {}

	inline const int GetBone() const { return bone; }
	inline const Vector* const GetKneeDir() const { return &kneeDir; }

private:
	int bone;
	Vector kneeDir;
};

class IModelIKChain
{
public:
	IModelIKChain() = default;
	IModelIKChain(const r1::mstudioikchain_t* const pIKChain) : name(nullptr), unk(cos(45.0f))
	{
		assertm(pIKChain->numlinks == IKLINK_COUNT, "invalid ik chain");

		name = AllocStudioString(pIKChain->pszName());

		links[IKLINK_THIGH] = IModelIKLink(pIKChain->pLink(IKLINK_THIGH));
		links[IKLINK_KNEE] = IModelIKLink(pIKChain->pLink(IKLINK_KNEE));
		links[IKLINK_FOOT] = IModelIKLink(pIKChain->pLink(IKLINK_FOOT));
	}
	IModelIKChain(const r2::mstudioikchain_t* const pIKChain) : name(nullptr), unk(pIKChain->unk_10)
	{
		assertm(pIKChain->numlinks == IKLINK_COUNT, "invalid ik chain");

		name = AllocStudioString(pIKChain->pszName());

		links[IKLINK_THIGH] = IModelIKLink(pIKChain->pLink(IKLINK_THIGH));
		links[IKLINK_KNEE] = IModelIKLink(pIKChain->pLink(IKLINK_KNEE));
		links[IKLINK_FOOT] = IModelIKLink(pIKChain->pLink(IKLINK_FOOT));
	}
	~IModelIKChain()
	{
		FreeAllocArray(name);
	}

	enum LinkType_t
	{
		IKLINK_INVALID = -1,

		IKLINK_THIGH,
		IKLINK_KNEE,
		IKLINK_FOOT,

		IKLINK_COUNT
	};

	inline const char* const GetName() const { return name; }
	inline const float GetUnkAngle() const { return unk; }
	inline const IModelIKLink* const GetIKLink(const LinkType_t link) const
	{
		assertm(link < IKLINK_COUNT && link > IKLINK_INVALID, "invalid link index");
		return &links[link];
	}

	IModelIKChain& operator=(const IModelIKChain&&) = delete;
	IModelIKChain& operator=(IModelIKChain&& chain) noexcept
	{
		if (this != &chain)
		{
			memcpy_s(links, sizeof(links), chain.links, sizeof(chain.links));

			name = chain.name;
			unk = chain.unk;

			chain.name = nullptr;
		}

		return *this;
	}

private:
	char* name;
	float unk;

	// while this could be dynamic, it's hardcoded throughout all of source and reSource to assume it's 3
	// I'd imagine the original intent was to add more types with varied links, but that never happened
	IModelIKLink links[IKLINK_COUNT];
};


// 
// Model Animation Data
//

enum eIModelAnimTrackFlags : uint16_t
{
	// does not use default (bone) values
	TRACK_POS = 0x1,
	TRACK_ROT = 0x2,
	TRACK_SCL = 0x4,
};

class IModelAnimationTrack
{
public:
	IModelAnimationTrack() = default;
	IModelAnimationTrack(const int frameCount);
	~IModelAnimationTrack();

	inline const int GetBone() const { return bone; }
	inline const char* GetBoneName() const { return name; }
	void GetFrame(const int frameIdx, Vector& pos, Quaternion& rot, Vector& scale) const;
	void GetFrameLast(Vector& pos, Quaternion& rot, Vector& scale) const;
	inline const int GetFrameCount() const { return frameCount; }
	inline const uint16_t GetFlags() const { return flags; }

	inline void SetBone(const int boneIdx) { bone = boneIdx; }
	void SetBoneName(const char* nameIn);
	__forceinline void SetFlags(const uint16_t flagIn) { flags |= flagIn; }

	inline const bool HasData() const { return GetFrameCount() > 0; }

	void Init(const int frameCountIn, const int boneIndex, const char* nameIn);
	void AddFrame(const int frameIdx, const Vector& pos, const Quaternion& rot, const Vector& scale);

private:
	struct frame_t
	{
		frame_t() : position(0.0f), rotation(0.0f, 0.0f, 0.0f, 1.0f), scale(1.0f) {};

		Vector position;
		Quaternion rotation;
		Vector scale;
	};

	frame_t* frames;
	int frameCount;

	int bone;
	const char* name;

	uint16_t flags;

	//inline const frame_t* FramePtr() const { return frames; }
};

// anim track like normal animations, might end up swapping this to just be IModelAnimationTrack
class IModelMovementTrack
{
public:
	IModelMovementTrack(const int frameCountIn);
	~IModelMovementTrack();

	inline const int GetFrameCount() const { return frameCount; }
	void GetFrame(const int frameIdx, Vector& pos, QAngle& rot) const;
	void AddFrame(const int frameIdx, const Vector& pos, const QAngle& rot);

private:
	struct frame_t
	{
		Vector positions;
		QAngle rotations;
	};

	frame_t* frames;
	const int frameCount;
};

// compressed ik errors are also a thing, but I don't know how they work
class IModelIKRule
{
public:
	IModelIKRule() = default;
	IModelIKRule(const r1::mstudioikrule_t* const pIKRule) : attachment(nullptr), compressedikerror(nullptr), ikerror(nullptr), index(pIKRule->index), type(pIKRule->type), chain(pIKRule->chain), bone(pIKRule->bone), slot(pIKRule->slot),
		height(pIKRule->height), radius(pIKRule->radius), floor(pIKRule->floor), pos(pIKRule->pos), q(pIKRule->q),
		iStart(pIKRule->iStart), start(pIKRule->start), peak(pIKRule->peak), tail(pIKRule->tail), end(pIKRule->end), contact(pIKRule->contact), drop(pIKRule->drop), top(pIKRule->top), endHeight(pIKRule->endHeight)
	{
		assertm(drop == 0.0f, "drop was used");
		assertm(top == 0.0f, "top was used");

		const char* const pszAttachment = pIKRule->pszAttachment();
		if (pszAttachment)
		{
			attachment = AllocStudioString(pszAttachment);
		}

		// todo
		if (pIKRule->compressedikerrorindex)
		{
			//assertm(false, "not implemented");
		}

		if (pIKRule->ikerrorindex)
		{
			assertm(false, "not implemented");
		}
	}
	IModelIKRule(const r2::mstudioikrule_t* const pIKRule) : attachment(nullptr), compressedikerror(nullptr), ikerror(nullptr), index(pIKRule->index), type(pIKRule->type), chain(pIKRule->chain), bone(pIKRule->bone), slot(pIKRule->slot),
		height(pIKRule->height), radius(pIKRule->radius), floor(pIKRule->floor), pos(pIKRule->pos), q(pIKRule->q),
		iStart(pIKRule->iStart), start(pIKRule->start), peak(pIKRule->peak), tail(pIKRule->tail), end(pIKRule->end), contact(pIKRule->contact), drop(pIKRule->drop), top(pIKRule->top), endHeight(pIKRule->endHeight)
	{
		assertm(drop == 0.0f, "drop was used");
		assertm(top == 0.0f, "top was used");

		const char* const pszAttachment = pIKRule->pszAttachment();
		if (pszAttachment)
		{
			attachment = AllocStudioString(pszAttachment);
		}

		// todo
		if (pIKRule->compressedikerrorindex)
		{
			//assertm(false, "not implemented");
		}

		if (pIKRule->ikerrorindex)
		{
			assertm(false, "not implemented");
		}
	}
	~IModelIKRule()
	{
		FreeAllocArray(attachment);
		FreeAllocVar(compressedikerror);
		FreeAllocVar(ikerror);
	}

	IModelIKRule& operator=(const IModelIKRule&&) = delete;
	IModelIKRule& operator=(IModelIKRule&& ikrule) noexcept
	{
		if (this != &ikrule)
		{
			memcpy_s(this, sizeof(IModelIKRule), &ikrule, sizeof(IModelIKRule));

			attachment = ikrule.attachment;
			compressedikerror = ikrule.compressedikerror;
			ikerror = ikrule.ikerror;

			ikrule.attachment = nullptr;
			ikrule.compressedikerror = nullptr;
			ikrule.ikerror = nullptr;
		}

		return *this;
	}

	enum Type_t : int
	{
		IKRULE_SELF			= 1,
		IKRULE_WORLD		= 2,
		IKRULE_GROUND		= 3,
		IKRULE_RELEASE		= 4,
		IKRULE_ATTACHMENT	= 5,
		IKRULE_UNLATCH		= 6,
	};

	const char* const GetAttachment() const { return attachment; }

	inline const int GetType() const { return type; }
	inline const int GetChain() const { return chain; }
	inline const int GetBone() const { return bone; }
	inline const int GetSlot() const { return slot; }

	inline const float GetHeight() const { return height; }
	inline const float GetRadius() const { return radius; }
	inline const float GetFloor() const { return floor; }

	inline const Vector* const GetPos() const { return &pos; }
	inline const Quaternion* const GetQ() const { return &q; }

	inline const float GetStart() const { return start; }
	inline const float GetPeak() const { return peak; }
	inline const float GetTail() const { return tail; }
	inline const float GetEnd() const { return end; }

	inline const float GetContact() const { return contact; }
	inline const float GetDrop() const { return drop; }
	inline const float GetTop() const { return top; }

	inline const float GetEndHeight() const { return endHeight; }

private:
	char* attachment;
	void* compressedikerror;
	void* ikerror;

	int index;
	int type;
	int chain;
	int bone;
	
	int slot; // iktarget slot. Usually same as chain.
	float height;
	float radius;
	float floor;
	Vector pos;
	Quaternion q;
	
	int iStart;
	
	float start; // beginning of influence
	float peak; // start of full influence
	float tail; // end of full influence
	float end; // end of all influence
	
	// drop & top seem to be not set anywhere
	float contact; // frame footstep makes ground concact
	float drop; // how far down the foot should drop when reaching for IK
	float top;	// top of the foot box
	
	float endHeight; // new in v52
	   // titan_buddy_mp_core.mdl
};

class IModelMovement
{
public:
	IModelMovement() = default;
	IModelMovement(const r1::mstudiomovement_t* const pMovement) : endframe(pMovement->endframe), motionflags(pMovement->motionflags), v0(pMovement->v0), v1(pMovement->v1), angle(pMovement->angle), vector(pMovement->vector), position(pMovement->position) {}
	IModelMovement(const r2::mstudiomovement_t* const pMovement) : endframe(pMovement->endframe), motionflags(pMovement->motionflags), v0(pMovement->v0), v1(pMovement->v1), angle(pMovement->angle), vector(pMovement->vector), position(pMovement->position) {}

	inline const int GetEndFrame() const { return endframe; }
	inline const int GetMotionFlags() const { return motionflags; }

private:
	int		endframe;
	int		motionflags;
	float	v0;			// velocity at start of block
	float	v1;			// velocity at end of block
	float	angle;		// YAW rotation at end of this blocks movement
	Vector	vector;		// movement vector relative to this blocks initial angle
	Vector	position;	// relative to start of animation???
};

class IModelFrameMovement
{
public:
	IModelFrameMovement(const r1::mstudioframemovement_t* const pFrameMovement) : sectionCount(0), sectionFrames(0)
	{
		memcpy_s(scale, sizeof(scale), pFrameMovement->scale, sizeof(pFrameMovement->scale));
		memcpy_s(offset, sizeof(offset), pFrameMovement->offset, sizeof(pFrameMovement->offset));
	}
	IModelFrameMovement(const r2::mstudioframemovement_t* const pFrameMovement) : sectionCount(0), sectionFrames(0)
	{
		memcpy_s(scale, sizeof(scale), pFrameMovement->scale, sizeof(pFrameMovement->scale));
		memcpy_s(offset, sizeof(offset), pFrameMovement->offset, sizeof(pFrameMovement->offset));
	}

private:
	float scale[4];
	int sectionCount;
	int sectionFrames;

	union
	{
		int* sections;
		short offset[4];
	};
};

// for animations and sequences
// some only get set on sequences and vice versa
typedef uint64_t IModelAnimFlags_t;
enum eIModelAnimFlags : IModelAnimFlags_t
{
	IMODELANIM_FLAG_NONE,

	IMODELANIM_FLAG_LOOPING		= 0x0001,		// ending frame should be the same as the starting frame
	IMODELANIM_FLAG_SNAP		= 0x0002,		// do not interpolate between previous animation and this one
	IMODELANIM_FLAG_DELTA		= 0x0004,		// this sequence "adds" to the base sequences, not slerp blends
	IMODELANIM_FLAG_AUTOPLAY	= 0x0008,		// temporary flag that forces the sequence to always play
	IMODELANIM_FLAG_POST		= 0x0010,		// 
	IMODELANIM_FLAG_ALLZEROS	= 0x0020,		// this animation/sequence has no real animation data
	IMODELANIM_FLAG_FRAMEANIM	= 0x0040,		// animation is encoded as by frame x bone instead of RLE bone x frame
	IMODELANIM_FLAG_CYCLEPOSE	= 0x0080,		// cycle index is taken from a pose parameter index
	IMODELANIM_FLAG_REALTIME	= 0x0100,		// cycle index is taken from a real-time clock, not the animations cycle index
	IMODELANIM_FLAG_LOCAL		= 0x0200,		// sequence has a local context sequence
	IMODELANIM_FLAG_HIDDEN		= 0x0400,		// don't show in default selection views
	IMODELANIM_FLAG_OVERRIDE	= 0x0800,		// a forward declared sequence (empty)
	IMODELANIM_FLAG_ACTIVITY	= 0x1000,		// Has been updated at runtime to activity index
	IMODELANIM_FLAG_EVENT		= 0x2000,		// Has been updated at runtime to event index on server
	IMODELANIM_FLAG_WORLD		= 0x4000,		// sequence blends in worldspace
	IMODELANIM_FLAG_NOFORCELOOP		= 0x8000,	// do not force the animation loop
	IMODELANIM_FLAG_EVENT_CLIENT	= 0x10000,	// Has been updated at runtime to event index on client
	IMODELANIM_FLAG_HAS_SCALE		= 0x20000,	// only appears on anims with scale, used for quick lookup in ScaleBones, only reason this should be check is if there has been scale data parsed in, otherwise it is pointless (see ScaleBones checking if scale is 1.0f).
	IMODELANIM_FLAG_FRAMEMOVEMENT	= 0x40000,	// framemovements are only read if this flag is present
	IMODELANIM_FLAG_SINGLEFRAME		= 0x80000,	// this animation/sequence only has one frame of animation data
	IMODELANIM_FLAG_BPANIM			= 0x100000, // animation uses bluepoint's custom animation data
	IMODELANIM_FLAG_DATAPOINTANIM	= 0x200000, // animation uses a packing method which adjusts off of framepoints
	

	IMODELANIM_FLAG_SUPPGEST		= 0x10000000,	// (0x40) fills spot 0x40 (STUDIO_FRAMEANIM in r1, unused in r2), unknown, suppgest? set when suppgest is used on option line.
													// (0x40) 'suppress gestures' (emotes?) used in a lot of finishers so makes sense. there are sequences prefixed with 'gesture_', and activities with gesture in their name
	IMODELANIM_FLAG_HAS_ANIM		= 0x20000000,	// (0x20000) in apex STUDIO_HAS_SCALE only gets written on sequences, and this flag only gets written on animations		
	IMODELANIM_FLAG_UNK100000		= 0x40000000,	// (0x100000) in apex this flag seems to be used for idle sequences on reactive skins		

	// flags set on parsing, not from studio flags
	IMODELANIM_FLAG_MOVEMENTTRACK	= 0x1000000000,
};

class IModelAnimation
{
public:
	IModelAnimation() = default;
	IModelAnimation(const r1::studiohdr_t* const pHdr, const r1::mstudioanimdesc_t* const pAnimDesc, const StudioLooseData_t* const looseData);
	IModelAnimation(const r2::studiohdr_t* const pHdr, const r2::mstudioanimdesc_t* const pAnimDesc);
	~IModelAnimation();

	inline const char* const GetName() const { return name + IsSeqDeclared(); }
	inline const float GetFrameRate() const { return frameRate; }
	inline const int GetFrameCount() const { return frameCount; }
	inline const uint32_t GetFrameCount_UINT() const { return static_cast<uint32_t>(frameCount); }
	inline const IModelAnimFlags_t GetFlags() const { return flags; }

	inline const int GetMovementCount() const { return movementCount; }
	inline const IModelMovement* const GetMovement(const int index) const { return movements + index; }

	inline const int GetIKRuleCount() const { return ikRuleCount; }
	inline const IModelIKRule* const GetIKRule(const int index) const { return ikRules + index; }

	inline const int GetSectionFrames() const { return sectionFrames; }
	inline const int GetSectionCount() const { return sectionCount; }
	inline const int GetLocalSectionCount() const { return localSectionCount; }
	inline const int GetZeroFrameSpan() const { return zeroFrameSpan; }
	inline const int GetZeroFrameCount() const { return zeroFrameCount; }

	inline const float GetFrameOffset(const int frameIdx) const { return static_cast<float>((GetDuration() / GetFrameCount()) * frameIdx); } // offset in seconds to this frame
	inline const float GetDuration() const { return static_cast<float>(GetFrameCount() / GetFrameRate()); } // length in seconds of this animation

	inline const bool IsOverriden() const { return flags & IMODELANIM_FLAG_OVERRIDE; } // gets overwrote by external animation on load
	inline const bool IsSeqDeclared() const { return name[0] == '@'; }
	inline const bool IsNullName() const { return name[0] == '\0'; }

	inline const uint32_t GetBoneCount() const { return animTrackCount; }
	inline const IModelMovementTrack* GetMovementTrack() const { return movementTrack;  }
	inline const IModelAnimationTrack* GetAnimTrack(const int index) const { return animTracks + index; }
	inline const bool HasMovementTrack() const { return movementTrack && (flags & IMODELANIM_FLAG_MOVEMENTTRACK); }

	IModelAnimation& operator=(const IModelAnimation&& anim) = delete;
	IModelAnimation& operator=(IModelAnimation&& anim) noexcept
	{
		if (this != &anim)
		{
			memcpy_s(this, sizeof(IModelAnimation), &anim, sizeof(IModelAnimation));

			name = anim.name;

			movements = anim.movements;
			framemovement = anim.framemovement;
			ikRules = anim.ikRules;
			localHierarchies = anim.localHierarchies;

			animTracks = anim.animTracks;
			movementTrack = anim.movementTrack;

			anim.name = nullptr;

			anim.movements = nullptr;
			anim.framemovement = nullptr;
			anim.ikRules = nullptr;
			anim.localHierarchies = nullptr;

			anim.animTracks = nullptr;
			anim.movementTrack = nullptr;
		}

		return *this;
	}

private:
	char* name;

	float frameRate;
	int frameCount;

	IModelAnimFlags_t flags;

	int movementCount;
	IModelMovement* movements;
	IModelFrameMovement* framemovement;
	
	IModelIKRule* ikRules;
	int ikRuleCount;

	int localHierarchyCount;
	void* localHierarchies;

	int sectionFrames;		// max frames per section
	int sectionStallFrames;
	int16_t sectionCount;
	int16_t localSectionCount;	// one or more of the sections was stored locally
	int16_t zeroFrameSpan;
	int16_t zeroFrameCount;

	// parsed track data
	int animTrackCount;
	IModelAnimationTrack* animTracks;
	IModelMovementTrack* movementTrack; // on paper "framemovements" and normal source style "movements" should be properly extracted into this track.

	inline const float GetCycle(const int frame)
	{
		const float cycle = frameCount > 1 ? static_cast<float>(frame) / static_cast<float>(frameCount - 1) : 0.0f;
		assertm(isfinite(cycle), "cycle was nan");
		return cycle;
	}

	inline const bool HasStall() const { return sectionStallFrames > 0; }

	inline const int SectionCount(const bool useAnimData = false) const
	{
		const int useTrailSection = (flags & IMODELANIM_FLAG_DATAPOINTANIM) ? false : true; // rle anims have an extra section at the end, with only the last frame in full types (Quaternion48, Vector48, etc)
		const int useStallSection = HasStall();

		const int maxFrameIndex = (frameCount - sectionStallFrames - 1); // subtract to get the last frame index outside of stall

		const int sectionBase = (maxFrameIndex / sectionFrames); // basic section index
		const int sectionMaxIndex = sectionBase + useTrailSection + useStallSection; // max index of a section

		// [rika]: where we'd normally add one to get the count, in retail the first section omitted as it's expected to always be at offset 0 in animdata
		// [rika]: only retail animations will have this set, and it is not optional, if not set there is no animation data
		if (useAnimData)
			return sectionMaxIndex;

		return sectionMaxIndex + 1; // add one to make this max index a max count
	}
};

class IModelEvent
{
public:
	IModelEvent() = default;
	IModelEvent(const r1::mstudioevent_t* const pEvent);
	IModelEvent(const r2::mstudioevent_t* const pEvent);
	IModelEvent(const IModelEvent& eventIn);
	~IModelEvent();

	IModelEvent& operator=(const IModelEvent&& event_type) = delete;
	IModelEvent& operator=(IModelEvent&& event_type) noexcept
	{
		if (this != &event_type)
		{
			memcpy_s(this, sizeof(IModelEvent), &event_type, sizeof(IModelEvent));

			name = event_type.name;
			options = event_type.options;

			event_type.name = nullptr;
			event_type.options = nullptr;
		}

		return *this;
	}

	inline const char* const GetName() const { return name; }
	inline const char* const GetOptions() const { return options; }

	inline const float GetCycle() const { return cycle; }
	inline const float GetUnk() const { return unk; }
	inline const int GetEventId() const { return event; }
	
	inline const bool IsNewEventStyle() const { return type & NEW_EVENT_STYLE; }

private:
	char* name; // "event"
	char* options;

	float cycle;
	float unk; // as of apex v12.3
	int event;
	int type;
};

class IModelActMod
{
public:
	IModelActMod() = default;
	IModelActMod(const r1::mstudioactivitymodifier_t* const pActMod);
	IModelActMod(const r2::mstudioactivitymodifier_t* const pActMod);
	IModelActMod(const IModelActMod& actModIn);
	~IModelActMod();

	IModelActMod& operator=(const IModelActMod&& actmod) = delete;
	IModelActMod& operator=(IModelActMod&& actmod) noexcept
	{
		if (this != &actmod)
		{
			name = actmod.name;
			negate = actmod.negate;

			actmod.name = nullptr;
		}

		return *this;
	}

	inline const char* const GetName() const { return name; }
	inline const bool IsNegated() const { return negate; }

private:
	char* name;
	bool negate;
};

class IModelAutoLayer
{
public:
	IModelAutoLayer() = default;
	IModelAutoLayer(const r1::mstudioautolayer_t* const pAutoLayer) : sequence(0ull), iSequence(pAutoLayer->iSequence), iPose(pAutoLayer->iPose), flags(pAutoLayer->flags),
		start(pAutoLayer->start), peak(pAutoLayer->peak), tail(pAutoLayer->tail), end(pAutoLayer->end) {};
	IModelAutoLayer(const r2::mstudioautolayer_t* const pAutoLayer) : sequence(0ull), iSequence(pAutoLayer->iSequence), iPose(pAutoLayer->iPose), flags(pAutoLayer->flags),
		start(pAutoLayer->start), peak(pAutoLayer->peak), tail(pAutoLayer->tail), end(pAutoLayer->end) {};
	~IModelAutoLayer() {};

	inline const int GetSequenceIndex() const { return iSequence; }
	inline const int GetPoseIndex() const { return iPose; }

	inline const int GetFlags() const { return flags; }

	inline const float GetStart() const { return start; }
	inline const float GetPeak() const { return peak; }
	inline const float GetTail() const { return tail; }
	inline const float GetEnd() const { return end; }

private:
	AssetGuid_t sequence;
	short iSequence;
	short iPose;

	int flags;
	float start;	// beginning of influence
	float peak;		// start of full influence
	float tail;		// end of full influence
	float end;		// end of all influence
};

class IModelSequence
{
public:
	IModelSequence() = default;
	IModelSequence(const r1::studiohdr_t* const pHdr, const r1::mstudioseqdesc_t* const pSeqDesc);
	IModelSequence(const r2::studiohdr_t* const pHdr, const r2::mstudioseqdesc_t* const pSeqDesc);
	~IModelSequence();

	IModelSequence& operator=(const IModelSequence&& seq) = delete;
	IModelSequence& operator=(IModelSequence&& seq) noexcept
	{
		if (this != &seq)
		{
			memcpy_s(this, sizeof(IModelSequence), &seq, sizeof(IModelSequence));

			label = seq.label;
			activity = seq.activity;

			events = seq.events;
			blends = seq.blends;
			autoLayers = seq.autoLayers;
			weights = seq.weights;
			poseKeys = seq.poseKeys;
			ikLocks = seq.ikLocks;
			keyvalues = seq.keyvalues;
			activityModifiers = seq.activityModifiers;

			seq.label = nullptr;
			seq.activity = nullptr;

			seq.events = nullptr;
			seq.blends = nullptr;
			seq.autoLayers = nullptr;
			seq.weights = nullptr;
			seq.poseKeys = nullptr;
			seq.ikLocks = nullptr;
			seq.keyvalues = nullptr;
			seq.activityModifiers = nullptr;
		}

		return *this;
	}

	inline const char* const GetLabel() const { return label; }
	inline const char* const GetActivity() const { return activity; }
	inline const int GetActWeight() const { return actWeight; }

	inline const IModelAnimFlags_t GetFlags() const { return flags; }
	inline const bool IsOverriden() const { return flags & IMODELANIM_FLAG_OVERRIDE; } // gets overwrote by external animation on load

	inline const int GetEventCount() const { return eventCount; }
	inline const IModelEvent* const GetEvent(const int index) const { return events + index; }

	inline const int GetBlendCount() const { return blendCount; }
	inline const int16_t GetBlend(const int index) const { return GetAnimIndex(index); }

	inline const int* const GetGroupSize() const { return groupSize; }
	inline const int GetBlendWidth() const { return groupSize[0]; }
	inline const int GetBlendHeight() const { return groupSize[1]; }
	inline const int GetParamIndex(const int index) const { return paramIndex[index]; };
	inline const float GetParamStart(const int index) const { return paramStart[index]; }
	inline const float GetParamEnd(const int index) const { return paramEnd[index]; }
	 
	inline const float GetFadeInTime() const { return fadeInTime; }
	inline const float GetFadeOutTime() const { return fadeOutTime; }

	inline const int GetEntryNode() const { return localEntryNode; }
	inline const int GetExitNode() const { return localExitNode; }
	inline const int GetNodeFlags() const { return nodeFlags; }

	inline const float GetEntryPhase() const { return entryPhase; }
	inline const float GetExitPhase() const { return exitPhase; }

	inline const int GetAutoLayerCount() const { return autoLayerCount; }
	inline const IModelAutoLayer* const GetAutoLayer(const int index) const { return autoLayers + index; }

	inline const int GetWeightCount() const { return weightCount; }
	inline const float* const GetWeights() const { return weights; }
	inline const float GetWeight(const int index) const { return weights[index]; }

	inline const int GetIKLockCount() const { return ikLockCount; }
	inline const IModelIKLock* const GetIKLock(const int index) const { return ikLocks + index; }

	inline const char* const GetKeyValues() const { return keyvalues; }

	inline const int GetCyclePoseIndex() const { return cyclePoseIndex; }

	inline const int GetActModCount() const { return activityModifierCount; }
	inline const IModelActMod* const GetActMod(const int index) const { return activityModifiers + index; }

	inline const int GetIKResetMask() const { return ikResetMask; }

private:
	char* label;
	char* activity;

	IModelAnimFlags_t flags; // looping/non-looping flags

	int actWeight;

	int eventCount;
	IModelEvent* events;

	Vector bbmin; // per sequence bounding box
	Vector bbmax;

	// Index into array of shorts which is groupsize[0] x groupsize[1] in length
	int16_t* blends;
	int blendCount;
	inline const int16_t* const pAnimIndex(const int i) const { return blends + i; }
	inline const short GetAnimIndex(const int i) const { return *pAnimIndex(i); }
	const int AnimCount() const { return groupSize[0] * groupSize[1]; }

	// movementindex is UNUSED in all source games I can find, my guess it it's a holdover from goldsrc

	int groupSize[2];
	int paramIndex[2]; // X, Y, Z, XR, YR, ZR
	float paramStart[2]; // local (0..1) starting value
	float paramEnd[2]; // local (0..1) ending value
	int paramParent;

	float fadeInTime; // ideal cross fate in time (0.2 default)
	float fadeOutTime; // ideal cross fade out time (0.2 default)

	int localEntryNode; // transition node at entry
	int localExitNode; // transition node at exit
	int nodeFlags; // transition rules

	float entryPhase; // used to match entry gait
	float exitPhase; // used to match exit gait

	float lastFrame; // frame that should generation EndOfSequence

	int nextSeq; // auto advancing sequences
	int pose; // index of delta animation between end and nextseq

	int ikRuleCount;
	int autoLayerCount;
	IModelAutoLayer* autoLayers;
	inline const IModelAutoLayer* const pAutoLayer(const int i) const { return autoLayers + i; }

	float* weights;
	int weightCount;
	inline const float* const pWeightList() const { return weights; }
	inline const float weight(const int weightidx) const { return pWeightList()[weightidx]; }
	
	int ikLockCount;
	IModelIKLock* ikLocks;

	float* poseKeys;

	// Key values
	char* keyvalues;
	inline const char* pKeyValues() const { return keyvalues; }

	int cyclePoseIndex; // index of pose parameter to use as cycle index

	int activityModifierCount;
	IModelActMod* activityModifiers;
	inline const IModelActMod* const pActMod(const int i) const { return activityModifiers + i; }

	int ikResetMask;
	int unk;	// previously 'unk1'
};

class IModelPoseParameter
{
public:
	IModelPoseParameter() = default;
	IModelPoseParameter(const r1::mstudioposeparamdesc_t* const pPoseParam) : name(AllocStudioString(pPoseParam->pszName())), flags(pPoseParam->flags), start(pPoseParam->start), end(pPoseParam->end), loop(pPoseParam->loop) {}
	IModelPoseParameter(const r2::mstudioposeparamdesc_t* const pPoseParam) : name(AllocStudioString(pPoseParam->pszName())), flags(pPoseParam->flags), start(pPoseParam->start), end(pPoseParam->end), loop(pPoseParam->loop) {}

	~IModelPoseParameter()
	{
		FreeAllocArray(name);
	}

	inline const char* const GetName() const { return name; }
	inline const int GetFlags() const { return flags; }
	inline const float GetStart() const { return start; }
	inline const float GetEnd() const { return end; }
	inline const float GetLoop() const { return loop; }

	IModelPoseParameter& operator=(const IModelPoseParameter&&) = delete;
	IModelPoseParameter& operator=(IModelPoseParameter&& poseparm) noexcept
	{
		if (this != &poseparm)
		{
			memcpy_s(this, sizeof(IModelPoseParameter), &poseparm, sizeof(IModelPoseParameter));

			name = poseparm.name;
			poseparm.name = nullptr;
		}

		return *this;
	}

private:
	char* name;

	int flags;	// 'STUDIO_LOOPING' flag if looping is used
	float start;
	float end;
	float loop;
};

class IModelModelGroup
{
public:
	IModelModelGroup() = default;
	IModelModelGroup(const r1::mstudiomodelgroup_t* const pModelGroup) : label(nullptr), name(AllocStudioString(pModelGroup->pszName()))
	{
		assertm(pModelGroup->szlabelindex == 0, "model had label");
	}
	IModelModelGroup(const r2::mstudiomodelgroup_t* const pModelGroup) : label(nullptr), name(AllocStudioString(pModelGroup->pszName()))
	{
		assertm(pModelGroup->szlabelindex == 0, "model had label");
	}

	~IModelModelGroup()
	{
		FreeAllocArray(label);
		FreeAllocArray(name);
	}

	inline const char* const GetLabel() const { return label; }
	inline const char* const GetName() const { return name; }

	IModelModelGroup& operator=(const IModelModelGroup&&) = delete;
	IModelModelGroup& operator=(IModelModelGroup&& modelgroup) noexcept
	{
		if (this != &modelgroup)
		{
			label = modelgroup.label;
			name = modelgroup.name;

			modelgroup.label = nullptr;
			modelgroup.name = nullptr;
		}

		return *this;
	}

private:
	char* label; // unused in normal source but we support anyway
	char* name; // file name
};

class IModelAnimBlock
{
public:
	IModelAnimBlock() = default;
	IModelAnimBlock(const r1::mstudioanimblock_t* const pAnimBlock) : datastart(pAnimBlock->datastart), dataend(pAnimBlock->dataend), datasize(dataend - datastart) {}
 
	inline const int GetSize() const { return datasize; }

private:
	int datastart;
	int dataend;

	int datasize;
};


//
// Model Vertex Data
//

typedef uint32_t IModelFaceIndice;
constexpr size_t IMODELFACE_maxLocalIndices = 5ull;	// local
constexpr size_t IMODELFACE_maxIndices = 32ull; // soft cap

struct IModelFace
{
	IModelFace() = default;
	IModelFace(const IModelFaceIndice numIndices, const IModelFaceIndice a, const IModelFaceIndice b, const IModelFaceIndice c, const IModelFaceIndice d);
	IModelFace(const IModelFaceIndice numIndices, const IModelFaceIndice* const pIndices);
	IModelFace(const IModelFace& face);
	~IModelFace()
	{
		FreeAllocArray(indiceExtra);
	}

	IModelFaceIndice indiceCount;
	IModelFaceIndice indices[IMODELFACE_maxLocalIndices];
	IModelFaceIndice* indiceExtra; // if we need more indices allocate here. maintains current size (32bytes) and allows for common polygons to be created without memory allocation

	static constexpr size_t indiceSize = sizeof(indices);

	inline const bool IsTri() const { return indiceCount == 3; }
	inline const bool IsQuad() const { return indiceCount == 4; }
	inline const bool IsNGon() const { return (IsTri() || IsQuad()) ? false : true; }

	inline const IModelFaceIndice GetIndiceCount() const { return indiceCount; }
	inline const IModelFaceIndice GetIndice(const IModelFaceIndice idx) const
	{
		if (IMODELFACE_maxLocalIndices > idx)
		{
			return indices[idx];
		}

		assertm(indiceExtra, "extra indices was invalid");
		return indiceExtra[idx - IMODELFACE_maxLocalIndices];
	}

	IModelFace& operator=(const IModelFace&) = delete;
	IModelFace& operator=(IModelFace&& face) noexcept
	{
		if (this != &face)
		{
			indiceCount = face.indiceCount;

			memcpy_s(indices, indiceSize, face.indices, indiceSize);

			indiceExtra = face.indiceExtra;
			face.indiceExtra = nullptr;
		}

		return *this;
	}

	void FlipOrder();
};

struct IModelVertexBoneWeight
{
	IModelVertexBoneWeight(int b, float w) : bone(b), weight(w) {};
	IModelVertexBoneWeight(int b) : bone(b), weight(1.f) {};
	IModelVertexBoneWeight() : bone(0), weight(0.f) {};
	~IModelVertexBoneWeight() {};

	int bone;
	float weight;
};

class IModelMesh;
struct IModelVertex
{
public:
	IModelVertex() = default;
	~IModelVertex();

	inline const Vector& GetPosition() const { return position; }
	inline const Vector& GetNormal() const { return normal; }
	inline void SetNormal(const Vector& norm) { normal = norm; }
	inline void AccumulateNormal(const Vector& norm) { normal += norm; }
	inline const Vector4D& GetTangent() const { return tangent; }

	inline const uint32_t GetWeightCount() const { return weightCount; }
	inline const uint32_t GetWeightIndex() const { return weightIndex; }
	inline const void SetWeightCount(const uint32_t count) { weightCount = count; }
	inline const void SetWeightIndex(const uint32_t index) { weightIndex = index; }

	static void ParseFromVTX(IModelVertex* const vertex, const uint32_t vertexIndex, IModelMesh* const mesh, const int origId, const vvd::mstudiovertex_t* const pSrcVerts, const Vector4D* const pSrcTangs, const Color32* const pSrcColors, const Vector2D* const pSrcTexcoords);
	static void ParseFromVTX(IModelVertex* const vertex, const uint32_t vertexIndex, IModelMesh* const mesh, const OptimizedModel::Vertex_t* const pVert, const vvd::mstudiovertex_t* const pSrcVerts, const Vector4D* const pSrcTangs, const Color32* const pSrcColors, const Vector2D* const pSrcTexcoords,
		const OptimizedModel::BoneStateChangeHeader_t* const pBoneStates, const bool isHwSkinned);
	static void ParseFromVTX(IModelVertex* const vertex, const uint32_t vertexIndex, IModelMesh* const mesh, const OptimizedModel::Vertex_t* const pVert, const vvd::mstudiovertex_t* const pSrcVerts, const Vector4D* const pSrcTangs, const Color32* const pSrcColors, const Vector2D* const pSrcTexcoords,
		const vvw::mstudioboneweightextra_t* const pSrcWeights);
	static void ParseFromIVPS(IModelVertex* const vertex, IModelMesh* const mesh, const Vector* const pPos, const IModelVertexBoneWeight* const pWeight);

	inline static void InvertTexcoord(Vector2D& texcoord)
	{
		texcoord.y = 1.0f - texcoord.y;
	}

	inline const Vector2D* const GetTexcoordForVertex(const uint32_t texcoordIdx, const uint32_t texcoordWidth, const Vector2D* const texcoords, const uint32_t vertIdx) const
	{
		if (texcoordIdx >= texcoordWidth)
		{
			assertm(false, "invalid texcoord index");
			return nullptr;
		}

		const Vector2D* const out = texcoords + (vertIdx * texcoordWidth) + texcoordIdx;
		return out;
	}

private:
	Vector position;
	Vector normal;
	Vector4D tangent;

	uint32_t weightCount : 8;	// max 16
	uint32_t weightIndex : 24;

	static void ParseWeight(IModelVertex* const vertex, IModelMesh* const mesh, const OptimizedModel::Vertex_t* const pVert, const vvd::mstudiovertex_t* const pSrcVert, const OptimizedModel::BoneStateChangeHeader_t* const pBoneStates, const bool isHwSkinned);
	static void ParseWeight(IModelVertex* const vertex, IModelMesh* const mesh, const vvd::mstudiovertex_t* const pSrcVert, const vvw::mstudioboneweightextra_t* const pSrcWeights);
	static void ParseExtraWeight(const vvd::mstudiovertex_t* const pSrcVert, const vvw::mstudioboneweightextra_t* const pExtraBoneWeights, const int idx, float& weight, int& bone);
};


//
// Model Mesh Data
//

class IModelPhysics;
class IModelMapCollision;
class IModelPerTriAABB;
class IModelUIPanel;

enum eIModelTextureType : int
{
	IMODELTEXTURE_UIPANEL = -3,
	IMODELTEXTURE_PHYSICS = -2,
	IMODELTEXTURE_INVALID = -1,

	IMODELTEXTURE_NORMAL = 0,
};

class IModelTexture
{
public:
	IModelTexture() = default;
	IModelTexture(const r1::mstudiotexture_t* const pTexture) : name(AllocStudioString(pTexture->pszName())), material(0ull), flags(pTexture->unused_flags), type(MaterialShaderType_t::_MAT_SHADER_TYPE_INVALID) {};
	IModelTexture(const r2::mstudiotexture_t* const pTexture) : name(AllocStudioString(pTexture->pszName())), material(0ull), flags(pTexture->unused_flags), type(MaterialShaderType_t::_MAT_SHADER_TYPE_INVALID) {};
	IModelTexture(const r5::mstudiotexture_t* const pTexture, const MaterialShaderType_t shaderType) : name(AllocStudioString(pTexture->pszName())), material(pTexture->material), flags(0), type(shaderType) {};
	IModelTexture(const char* const ct_name, const AssetGuid_t ct_material, const int ct_flags, const MaterialShaderType_t ct_type) : name(AllocStudioString(ct_name)), material(ct_material), flags(ct_flags), type(ct_type) {}

	~IModelTexture()
	{
		FreeAllocArray(name);
	};

	const char* GetName() const { return name; }

	IModelTexture& operator=(const IModelTexture&& texture) = delete;
	IModelTexture& operator=(IModelTexture&& texture) noexcept
	{
		if (this != &texture)
		{
			memcpy_s(this, sizeof(IModelTexture), &texture, sizeof(IModelTexture));

			name = texture.name;
			texture.name = nullptr;
		}

		return *this;
	}

private:
	char* name;
	AssetGuid_t material; // TODO: I wanna add hashing for r2 because it's easy peasy

	int flags; // used for parsing materials in studiomdl
	MaterialShaderType_t type; // shader type for apex legends
};

static const IModelTexture s_TexturePhysics("phys", 0ull, 0, MaterialShaderType_t::_MAT_SHADER_TYPE_INVALID);
static const IModelTexture s_TextureUIPanel("ui_panel", 0ull, 0, MaterialShaderType_t::_MAT_SHADER_TYPE_INVALID);


constexpr const char* const s_SkinDefaultName = "";
class IModelSkin
{
public:
	IModelSkin() = default;
	IModelSkin(const int16_t* const skin, const int numSkinRef, const char* const skinName = nullptr)
	{
		int16_t* const tmp = new int16_t[numSkinRef]{};

		const size_t skinFamilySize = sizeof(int16_t) * numSkinRef;
		memcpy_s(tmp, skinFamilySize, skin, skinFamilySize);
		indices = tmp;

		ParseSkinName(skinName);
	}

	~IModelSkin()
	{
		
		if (name != s_SkinDefaultName)
		{
			FreeAllocArray(name);
		}

		FreeAllocArray(indices);
	}

	const char* const GetName() const { return name; }
	const int16_t* const GetIndices() const { return indices; }

	IModelSkin& operator=(const IModelSkin&& skin) = delete;
	IModelSkin& operator=(IModelSkin&& skin) noexcept
	{
		if (this != &skin)
		{
			name = skin.name;
			indices = skin.indices;

			skin.name = nullptr;
			skin.indices = nullptr;
		}

		return *this;
	}

private:
	const char* name;
	const int16_t* indices;

	void ParseSkinName(const char* const skinName)
	{
		if (skinName == nullptr)
		{
			name = s_SkinDefaultName;
			return;
		}

		name = AllocStudioString(skinName);
	}
};

typedef uint32_t IModelMeshFlags_t;

enum eIModelMeshFlags : IModelMeshFlags_t
{
	IMODELMESH_FLAG_NONE	= 0x0,

	// indices
	IMODELMESH_FLAG_TRI		= 0x1,
	IMODELMESH_FLAG_QUAD	= 0x2,
	IMODELMESH_FLAG_NGON	= 0x4,

	// misc
	IMODELMESH_FLAG_LARGE	= 0x10, // too fat for packed vertices (positions)

	// vertex data, may add some if other datatypes/flags are figured out for vg
	IMODELMESH_FLAG_POS		= 0x100,
	IMODELMESH_FLAG_NORM	= 0x200,
	IMODELMESH_FLAG_TAN		= 0x400,
	IMODELMESH_FLAG_COLOR	= 0x800,
	IMODELMESH_FLAG_WEIGHTS	= 0x1000,	// if not set, assumes origin bone with weight of 1.0f

	// TODO: make these better to support many texcoords
	IMODELMESH_FLAG_TEXCOORD_BASE = 0x10000,

	IMODELMESH_FLAG_TEXCOORD0	= IMODELMESH_FLAG_TEXCOORD_BASE << 0,
	IMODELMESH_FLAG_TEXCOORD2	= IMODELMESH_FLAG_TEXCOORD_BASE << 2,
	IMODELMESH_FLAG_TEXCOORD3	= IMODELMESH_FLAG_TEXCOORD_BASE << 3,
};

constexpr IModelMeshFlags_t IMODEL_defaultMeshFlags_VTX = (IMODELMESH_FLAG_POS | IMODELMESH_FLAG_NORM | IMODELMESH_FLAG_TAN | IMODELMESH_FLAG_WEIGHTS | IMODELMESH_FLAG_TEXCOORD0);

class IModelMeshData
{
public:
	IModelMeshData(const uint32_t vertexCount, const uint32_t indiceCount, const uint16_t weightsPerVertex, const uint16_t texcoordsPerVertex, const bool useVertexColor, char* const tempBuf);
	~IModelMeshData();

	char* buffer;

	IModelVertex* vertices;
	IModelFace* indices;
	IModelFace* triangles;

	// optional data
	IModelVertexBoneWeight* weights;
	Color32* colors;
	Vector2D* texcoords;

	void ShrinkData(const uint32_t vertexCount, const uint32_t indiceCount, const uint32_t triangleCount, const uint32_t weightCount, const uint16_t texcoordsPerVertex, const bool useVertexColor)
	{
		const size_t shrinkSize = RequiredSize(vertexCount, indiceCount, triangleCount, weightCount, texcoordsPerVertex, useVertexColor);
		char* const tmp = new char[shrinkSize];

		char* current = tmp;

		const size_t vertexSize = sizeof(IModelVertex) * vertexCount;
		memcpy_s(current, vertexSize, vertices, vertexSize);
		vertices = reinterpret_cast<IModelVertex*>(current);
		current += vertexSize;

		const size_t indiceSize = sizeof(IModelFace) * indiceCount;
		memcpy_s(current, indiceSize, indices, indiceSize);
		indices = reinterpret_cast<IModelFace*>(current);
		current += indiceSize;

		if (triangles && triangleCount)
		{
			const size_t triangleSize = sizeof(IModelFace) * triangleCount;
			memcpy_s(current, triangleSize, triangles, triangleSize);
			triangles = reinterpret_cast<IModelFace*>(current);
			current += triangleSize;
		}

		if (colors && useVertexColor)
		{
			const size_t colorSize = sizeof(Color32) * vertexCount;
			memcpy_s(current, colorSize, colors, colorSize);
			colors = reinterpret_cast<Color32*>(current);
			current += colorSize;
		}

		if (texcoords && texcoordsPerVertex > 0u)
		{
			const size_t texcoordSize = sizeof(Vector2D) * (vertexCount * texcoordsPerVertex);
			memcpy_s(current, texcoordSize, texcoords, texcoordSize);
			texcoords = reinterpret_cast<Vector2D*>(current);
			current += texcoordSize;
		}

		if (weights && weightCount > 0u)
		{
			const size_t weightSize = sizeof(IModelVertexBoneWeight) * weightCount;
			memcpy_s(current, weightSize, weights, weightSize);
			weights = reinterpret_cast<IModelVertexBoneWeight*>(current);
			current += weightSize;
		}

		FreeAllocArray(buffer);
		buffer = tmp;
	}

private:
	const size_t RequiredSize(const uint32_t vertexCount, const uint32_t indiceCount, const uint32_t triangleCount, const uint32_t weightCount, const uint16_t texcoordsPerVertex, const bool useVertexColor)
	{
		size_t maxRequiredSize = (sizeof(IModelVertex) * vertexCount) + (sizeof(IModelFace) * indiceCount);
		maxRequiredSize += (sizeof(IModelFace) * triangleCount);
		maxRequiredSize += (sizeof(Vector2D) * (vertexCount * texcoordsPerVertex));
		maxRequiredSize += (sizeof(Color32) * (vertexCount * useVertexColor));
		maxRequiredSize += (sizeof(IModelVertexBoneWeight) * weightCount);

		return maxRequiredSize;
	}

};

class IModelMesh
{
public:
	IModelMesh() = default;
	IModelMesh(const uint32_t lodIndex, const IModelSourceFlags_t sourceFlags, const r1::mstudiomesh_t* const pStudioMesh, const OptimizedModel::MeshHeader_t* const pVertexMesh, const StudioLooseData_t* const pLooseData);
	IModelMesh(const uint32_t lodIndex, const IModelSourceFlags_t sourceFlags, const r2::mstudiomesh_t* const pStudioMesh, const OptimizedModel::MeshHeader_t* const pVertexMesh, const StudioLooseData_t* const pLooseData);
	IModelMesh(const uint32_t lodIndex, const IModelSourceFlags_t sourceFlags, const r5::mstudiomesh_t* const pStudioMesh, const OptimizedModel::MeshHeader_t* const pVertexMesh, const StudioLooseData_t* const pLooseData);
	IModelMesh(const IModel* const imodel, IModelPhysics* const physics, const ivps::phyheader_t* const pPHYS);
	IModelMesh(const IModel* const imodel, IModelMapCollision* const collision);
	IModelMesh(const IModel* const imodel, IModelPerTriAABB* const perTriAABB);
	IModelMesh(const IModel* const imodel, const r2::UIPanelMesh_s* const pUIMesh);
	IModelMesh(const IModel* const imodel, const r5::UIPanelMesh_s* const pUIMesh);
	~IModelMesh();

	inline const IModelMeshFlags_t GetFlags() const { return flags; }
	inline const int GetMaterialId() const { return material; }

	inline IModelMeshData* const GetData() { return data; }

	inline const bool EnsureTriangulation() const { return (data->triangles != nullptr) && (triangleCount > 0); }

	inline const uint32_t GetVertexCount() const { return vertexCount; }
	inline const uint32_t GetIndiceCount() const { return indiceCount; }
	inline const uint32_t GetTriangleCount() const { return triangleCount; }
	inline const uint32_t GetWeightCount() const { return weightCount; }
	inline const uint16_t GetTexcoordCount() const { return texcoordCount; }
	inline const uint16_t GetMaxVertBoneCount() const { return maxWeightsPerVert; }

	inline const IModelVertex* const GetVertex(const uint32_t idx) const { return data->vertices + idx; }
	inline const IModelFace* const GetIndice(const uint32_t idx) const { return data->indices + idx; }
	inline const IModelFace* const GetTriangle(const uint32_t idx) const { return data->triangles + idx; }
	inline const Color32* const GetColor(const uint32_t idx) const { assertm(data->colors, "colors was nullptr"); return data->colors + idx; }
	inline const Vector2D* const GetTexcoord(const uint32_t idx, const uint16_t texcoordIdx) const
	{
		assertm(texcoordIdx < texcoordCount, "texcoord out of range");
		assertm(data->texcoords, "texcoords was nullptr");

		return data->texcoords + (idx * texcoordCount) + texcoordIdx;
	}
	inline const IModelVertexBoneWeight* const GetWeight(const IModelVertex* const vertex, const uint32_t weight) const
	{
		assertm((vertex->GetWeightIndex() + weight) < weightCount, "weight out of range");
		assertm(weight < vertex->GetWeightCount(), "weight out of range");
		assertm(data->weights, "weights was nullptr");

		return data->weights + vertex->GetWeightIndex() + weight;
	}

	inline void AddWeights(const uint32_t numWeights) { weightCount += numWeights; }

	IModelMesh& operator=(const IModelMesh&) = delete;
	IModelMesh& operator=(IModelMesh&& mesh) noexcept
	{
		if (this != &mesh)
		{
			memcpy_s(this, sizeof(IModelMesh), &mesh, sizeof(IModelMesh));

			data = mesh.data;
			mesh.data = nullptr;
		}

		return *this;
	}

private:
	IModelMeshFlags_t flags;

	int material;	// index into a material array

	// a unique ordinal for this mesh
	int meshid;
	Vector center;

	IModelMeshData* data;

	uint64_t vertexCount : 24;
	uint64_t indiceCount : 20;
	uint64_t triangleCount : 20;
	uint32_t weightCount;

	uint16_t texcoordCount;
	uint16_t maxWeightsPerVert;

	inline void ParseSourceFlags(const IModelSourceFlags_t sourceFlags)
	{
		// bit shift?
		if (sourceFlags & IMODEL_FLAG_USES_VERTEX_COLOR)
		{
			flags |= eIModelMeshFlags::IMODELMESH_FLAG_COLOR;
		}

		if (sourceFlags & IMODEL_FLAG_USES_UV2)
		{
			flags |= eIModelMeshFlags::IMODELMESH_FLAG_TEXCOORD2;
			texcoordCount++;
		}
	}

	// for normal source
	inline void AddVertex(const OptimizedModel::Vertex_t* const pVert, const vvd::mstudiovertex_t* const pSrcVerts, const Vector4D* const pSrcTangs, const Color32* const pSrcColors, const Vector2D* const pSrcTexcoords,
		const OptimizedModel::BoneStateChangeHeader_t* const pBoneStates, const bool isHwSkinned)
	{
		const uint32_t vertexIndex = vertexCount;
		IModelVertex::ParseFromVTX(data->vertices + vertexIndex, vertexIndex, this, pVert, pSrcVerts, pSrcTangs, pSrcColors, pSrcTexcoords, pBoneStates, isHwSkinned);
		vertexCount++;
	}

	// for apex legends
	inline void AddVertex(const OptimizedModel::Vertex_t* const pVert, const vvd::mstudiovertex_t* const pSrcVerts, const Vector4D* const pSrcTangs, const Color32* const pSrcColors, const Vector2D* const pSrcTexcoords,
		const vvw::mstudioboneweightextra_t* const pSrcWeights)
	{
		const uint32_t vertexIndex = vertexCount;
		IModelVertex::ParseFromVTX(data->vertices + vertexIndex, vertexIndex, this, pVert, pSrcVerts, pSrcTangs, pSrcColors, pSrcTexcoords, pSrcWeights);
		vertexCount++;
	}

	// for ivps
	inline void AddVertex(const Vector* const pPos, const IModelVertexBoneWeight* const pWeight)
	{
		const uint32_t vertexIndex = vertexCount;
		IModelVertex::ParseFromIVPS(data->vertices + vertexIndex, this, pPos, pWeight);
		vertexCount++;
	}

	inline void AddIndice(const IModelFace& face)
	{
		data->indices[indiceCount] = IModelFace(face);
		indiceCount++;
	}

	inline void AddIndice(const IModelFaceIndice numIndices, const IModelFaceIndice* const pIndices)
	{
		data->indices[indiceCount] = IModelFace(numIndices, pIndices);
		indiceCount++;
	}

	void ShrinkData()
	{
		data->ShrinkData(vertexCount, indiceCount, triangleCount, weightCount, texcoordCount, flags & IMODELMESH_FLAG_COLOR);
	}

	void FromValveVertex(const OptimizedModel::MeshHeader_t* const pVertexMesh, const uint32_t lod, const int baseVertexOffset, const int studioVertCount, const bool isApex,
		const vvd::vertexFileHeader_t* const pVVD, const vvc::vertexColorFileHeader_t* const pVVC, const vvw::vertexBoneWeightsExtraFileHeader_t* const pVVW);

	const int FromIVPSNode(const ivps::compactledgenode_t* const pNode, uint32_t& maxVertexIndex);

	// ui panel stuff
	const bool ModelUIPanel_MatchVertex(const Vector& targetVertex, const Vector* const vertices, const int numVerts, IModelFaceIndice& indice, const float tolerance);
	template<typename Indices, typename Bounds> void ModelUIPanel_ParseLocatingVertices(const Indices* const pUIIndices, const Bounds* const pUIBounds, const Vector* const parsedVertices, Vector* const vertexResult);
	template<typename Mesh, typename Bounds> void ModelUIPanel_ParseForQuad(const Vector* const vertexResult, const Vector* const parsedVertices, const Mesh* const pUIMesh, const Bounds* const pUIBounds, const int i);

	void GenerateNormals();
	void TriangulateMesh();
};

class IModelLOD;
class IModelModel
{
public:
	IModelModel() = default;
	IModelModel(const IModelLOD* const lod, const IModelSourceFlags_t sourceFlags, const r1::mstudiomodel_t* const pStudioModel, const OptimizedModel::ModelLODHeader_t* const pVertexLOD,
		const StudioLooseData_t* const pLooseData, const char* const modelName, const char* const bodypartName, const bool hasLODs);
	IModelModel(const IModelLOD* const lod, const IModelSourceFlags_t sourceFlags, const r2::mstudiomodel_t* const pStudioModel, const OptimizedModel::ModelLODHeader_t* const pVertexLOD,
		const StudioLooseData_t* const pLooseData, const char* const modelName, const char* const bodypartName, const bool hasLODs);
	IModelModel(const IModelLOD* const lod, const IModelSourceFlags_t sourceFlags, const r5::mstudiomodel_t* const pStudioModel, const OptimizedModel::ModelLODHeader_t* const pVertexLOD,
		const StudioLooseData_t* const pLooseData, const char* const modelName, const char* const bodypartName, const bool hasLODs);
	IModelModel(const IModel* const imodel, IModelPhysics* const physics, const ivps::phyheader_t* const pPHYS);
	IModelModel(const IModel* const imodel, IModelMapCollision* const collision);
	IModelModel(const IModel* const imodel, IModelPerTriAABB* const perTriAABB);
	IModelModel(const IModel* const imodel, const r2::UIPanelHeader_s* const pUIPanel);
	IModelModel(const IModel* const imodel, const r5::UIPanelHeader_s* const pUIPanel);
	//IModelModel(const r2::UIPanelHeader_s* const pPanel, const r2::mstudiobone_t* const pBones);
	~IModelModel();

	inline const char* GetName() const { return name; }
	inline const uint32_t GetVertexCount() const { return vertexCount; } // total vertices across meshes
	inline const uint32_t GetIndiceCount() const { return indiceCount; } // total indices across meshes
	inline const uint32_t GetWeightCount() const { return weightCount; } // total indices across meshes
	inline const uint16_t GetMaxVertBoneCount() const { return maxVertWeights; }
	inline const uint16_t GetMaxTexcoordCount() const { return maxVertTexcoords; }

	inline const uint16_t GetMeshCount() const { return meshCount; }
	inline const IModelMesh* const GetMesh(const uint32_t idx) const { return meshes + idx; }

	IModelModel& operator=(const IModelModel&) = delete;
	IModelModel& operator=(IModelModel&& model) noexcept
	{
		if (this != &model)
		{
			memcpy_s(this, sizeof(IModelModel), &model, sizeof(IModelModel));

			name = model.name;
			unknown = model.unknown;
			meshes = model.meshes;

			model.name = nullptr;
			model.unknown = nullptr;
			model.meshes = nullptr;
		}

		return *this;
	}

private:
	const char* name;
	const char* unknown; // goes to bones sometimes

	int type; // what even is this var
	float boundingradius;

	IModelMesh* meshes;
	uint16_t meshCount;

	uint32_t vertexCount;
	uint32_t indiceCount;
	uint32_t weightCount;

	// per vertex
	uint16_t maxVertWeights;
	uint16_t maxVertTexcoords;
};

// for lod
class IModelMaterialReplacement
{
public:
	IModelMaterialReplacement() = default;
	IModelMaterialReplacement(const OptimizedModel::MaterialReplacementHeader_t* const pMaterialReplacement) : replacement(AllocStudioString(pMaterialReplacement->pMaterialReplacementName())), originalId(pMaterialReplacement->materialID) {}
	~IModelMaterialReplacement()
	{
		FreeAllocArray(replacement);
	}

	inline const char* const GetReplacement() const { return replacement; }
	inline const int GetOriginal() const { return originalId; }

	IModelMaterialReplacement& operator=(const IModelMaterialReplacement&&) = delete;
	IModelMaterialReplacement& operator=(IModelMaterialReplacement&& material) noexcept
	{
		if (this != &material)
		{
			replacement = material.replacement;
			originalId = material.originalId;

			material.replacement = nullptr;
		}

		return *this;
	}

private:
	char* replacement;
	int originalId;
};

constexpr float invalidLODSwitchPoint = -2.0f; // we can't use -1.0f as that's for shadow LODs
class IModelLOD
{
public:
	IModelLOD() = default;
	IModelLOD(const uint32_t lodIndex, const uint16_t numModels, const IModelSourceFlags_t sourceFlags, const r1::studiohdr_t* const pHdr, const StudioLooseData_t* const pLooseData);
	IModelLOD(const uint32_t lodIndex, const uint16_t numModels, const IModelSourceFlags_t sourceFlags, const r2::studiohdr_t* const pHdr, const StudioLooseData_t* const pLooseData);
	IModelLOD(const uint32_t lodIndex, const uint16_t numModels, const IModelSourceFlags_t sourceFlags, const r5::studiohdr_t* const pHdr, const StudioLooseData_t* const pLooseData);
	~IModelLOD();

	inline const float GetSwitchPoint() const { return switchPoint; }
	inline const uint32_t GetLODLevel() const { return lodLevel; }

	inline const IModelModel* const GetModel(const uint16_t index) const { return models + index; }
	const uint16_t GetModelCount() const { return modelCount; }
	inline const IModelMaterialReplacement* const GetMaterialReplacement(const uint32_t index) const { return materialReplacements + index; }
	inline const uint32_t GetMaterialReplacementCount() const { return materialReplacementCount; }

	inline const uint16_t GetMaxVertBoneCount() const { return maxBonesPerVert; }
	inline uint16_t& MaxVertBoneCount() { return maxBonesPerVert; }
	
	IModelLOD& operator=(const IModelLOD&) = delete;
	IModelLOD& operator=(IModelLOD&& lod) noexcept
	{
		if (this != &lod)
		{
			memcpy_s(this, sizeof(IModelLOD), &lod, sizeof(IModelLOD));

			this->models = lod.models;

			lod.models = nullptr;
		}

		return *this;
	}

private:
	float switchPoint;
	uint32_t lodLevel; // numeric index of this lod

	IModelModel* models;
	uint16_t modelCount;

	uint16_t maxBonesPerVert; // for getting the max required weights

	uint32_t materialReplacementCount;
	IModelMaterialReplacement* materialReplacements;

	void ParseMaterialReplacements(const OptimizedModel::FileHeader_t* const pVTX);
};

class IModelBodypart
{
public:
	IModelBodypart() = default;
	IModelBodypart(const r1::mstudiobodyparts_t* const pBodypart, uint16_t& currentModelIndex) : name(AllocStudioString(pBodypart->pszName())), base(pBodypart->base), modelCount(static_cast<uint16_t>(pBodypart->nummodels)), modelIndex(currentModelIndex)
	{
		currentModelIndex += static_cast<uint16_t>(pBodypart->nummodels);
	}
	IModelBodypart(const r2::mstudiobodyparts_t* const pBodypart, uint16_t& currentModelIndex) : name(AllocStudioString(pBodypart->pszName())), base(pBodypart->base), modelCount(static_cast<uint16_t>(pBodypart->nummodels)), modelIndex(currentModelIndex)
	{
		currentModelIndex += static_cast<uint16_t>(pBodypart->nummodels);
	}
	IModelBodypart(const r5::mstudiobodyparts_t* const pBodypart, uint16_t& currentModelIndex) : name(AllocStudioString(pBodypart->pszName())), base(pBodypart->base), modelCount(static_cast<uint16_t>(pBodypart->nummodels)), modelIndex(currentModelIndex)
	{
		currentModelIndex += static_cast<uint16_t>(pBodypart->nummodels);
	}
	~IModelBodypart()
	{
		FreeAllocArray(name);
	}

	inline const char* const GetName() const { return name; }
	inline const IModelModel* const GetModel(const uint16_t index, const IModelLOD* const lod) const { return lod->GetModel(modelIndex + index); }
	inline const uint16_t GetModelCount() const { return modelCount; }

	IModelBodypart& operator=(const IModelBodypart&) = delete;
	IModelBodypart& operator=(IModelBodypart&& bodypart) noexcept
	{
		if (this != &bodypart)
		{
			memcpy_s(this, sizeof(IModelBodypart), &bodypart, sizeof(IModelBodypart));

			this->name = bodypart.name;

			bodypart.name = nullptr;
		}

		return *this;
	}

private:
	const char* name;
	int base; // maybe don't store this?

	uint16_t modelCount;
	uint16_t modelIndex;
};


//
// Model Mesh Other
//

class IModelPhysics : public IModelModel
{
public:
	IModelPhysics(const IModel* const imodel, const ivps::phyheader_t* const pPHYS);
	~IModelPhysics()
	{

	}	

	inline const PhysicsModel::CParsedPhys* const GetParsedPhys() const { return &parsedPhysics; }
	inline void SetJointed(const bool hasJoints) { parsedPhysics.SetJointed(hasJoints); }
	inline void SetConcavePerJoint() { parsedPhysics.SetConcavePerJoint(); }
	inline void SetMaxConvexPieces(const int16_t numPieces) { parsedPhysics.SetMaxConvexPieces(numPieces); }

private:
	PhysicsModel::CParsedPhys parsedPhysics;
};

class IModelMapCollisionSide
{
public:
	IModelMapCollisionSide() = default;
	IModelMapCollisionSide(const r2::mstudiocollside_t* const pCollFace);

	IModelMapCollisionSide& operator=(const IModelMapCollisionSide&) = delete;
	IModelMapCollisionSide& operator=(const IModelMapCollisionSide&& side) noexcept
	{
		if (this != &side)
		{
			normal = side.normal;
			normalScale = side.normalScale;

			memcpy_s(edgeIndices, sizeof(edgeIndices), side.edgeIndices, sizeof(side.edgeIndices));
			memcpy_s(vertIndices, sizeof(vertIndices), side.vertIndices, sizeof(side.vertIndices));
		}

		return *this;
	}

	const uint8_t GetVertexCount() const { return vertCount; }
	const uint8_t GetVertexIndice(const uint8_t i) const { return vertIndices[i]; }

	const eIModelMeshFlags GetFaceType() const
	{
		assertm(vertCount > 2, "that's an edge not a side");

		switch (vertCount)
		{
		case 3:
		{
			return eIModelMeshFlags::IMODELMESH_FLAG_TRI;
		}
		case 4:
		{
			return eIModelMeshFlags::IMODELMESH_FLAG_QUAD;
		}
		default:
		{
			return eIModelMeshFlags::IMODELMESH_FLAG_NGON;
		}
		}
	}

	friend class IModelMapCollisionShape;

private:
	Vector normal;
	float normalScale;

	uint8_t edgeCount;
	uint8_t vertCount;

	// limit in code is 128 (I think)
	uint8_t edgeIndices[128];
	uint8_t vertIndices[128];
};

class IModelMapCollisionEdge
{
public:
	IModelMapCollisionEdge() = default;
	IModelMapCollisionEdge(const r2::mstudiocolledge_t* const pEdge) : origin(pEdge->origin), delta(pEdge->delta)
	{
		sideIndices[0] = pEdge->sideIndices[0];
		sideIndices[1] = pEdge->sideIndices[1];

		vertIndices[0] = pEdge->vertIndices[0];
		vertIndices[1] = pEdge->vertIndices[1];
	}

private:
	Vector origin;
	Vector delta;
	uint8_t sideIndices[2];
	uint8_t vertIndices[2];
};

// store some data about each shape!
class IModelMapCollisionShape
{
public:
	IModelMapCollisionShape() = default;
	IModelMapCollisionShape(const r2::mstudiocollhdr_t* const pCollHdr, const uint32_t bone);
	~IModelMapCollisionShape()
	{
		FreeAllocArray(sides);
		FreeAllocArray(edges);
		FreeAllocArray(vertices);
	}

	IModelMapCollisionShape& operator=(const IModelMapCollisionShape&) = delete;
	IModelMapCollisionShape& operator=(IModelMapCollisionShape&& shape) noexcept
	{
		if (this != &shape)
		{
			sideCount = shape.sideCount;
			sideAndQuirkyCount = shape.sideAndQuirkyCount;
			edgeCount = shape.edgeCount;
			vertCount = shape.vertCount;

			parent = shape.parent;

			sides = shape.sides;
			edges = shape.edges;
			vertices = shape.vertices;
			shape.sides = nullptr;
			shape.edges = nullptr;
			shape.vertices = nullptr;
		}

		return *this;
	}

	const int GetVertexCount() const { return vertCount; }
	const Vector& GetVertex(const int i) const { return vertices[i]; }
	const int GetSideCount() const { return sideCount; }
	const IModelMapCollisionSide* const GetSide(const int i) const { return sides + i; }

	const uint32_t GetParent() const { return parent; }

private:
	IModelMapCollisionSide* sides;
	IModelMapCollisionEdge* edges;
	Vector* vertices;

	int16_t sideCount;
	int16_t sideAndQuirkyCount;
	int16_t edgeCount;
	int16_t vertCount;
	
	uint32_t parent; // this is the bone
};

class IModelMapCollision : public IModelModel
{
public:
	IModelMapCollision(const IModel* const imodel, const r2::studiohdr_t* const pStudioHdr);
	~IModelMapCollision()
	{
		FreeAllocArray(shapes);
	}

	const int GetShapeCount() const { return shapeCount; }
	const IModelMapCollisionShape* const GetShape(const int i) const { return shapes + i; }

private:
	IModelMapCollisionShape* shapes;
	int shapeCount;
	bool isRigged;
};

class IModelPerTriAABBTri
{
public:
	IModelPerTriAABBTri() = default;
	IModelPerTriAABBTri(const r1::mstudiopertrileaf_t* const pLeaf, const r1::mstudiopertritri_t* const pTri) : vertexIndices()
	{
		vertexIndices[0] = pLeaf->vertexIndex + pTri->vertIndices[0];
		vertexIndices[1] = pLeaf->vertexIndex + pTri->vertIndices[1];
		vertexIndices[2] = pLeaf->vertexIndex + pTri->vertIndices[2];

		assertm(vertexIndices[0] != vertexIndices[1], "we have to parse this now");
	}
	IModelPerTriAABBTri(const r1::mstudiopertrileaf_v1_t* const pLeaf, const r1::mstudiopertritri_v1_t* const pTri) : vertexIndices()
	{
		vertexIndices[0] = pLeaf->vertexIndex + pTri->vertIndices[0];
		vertexIndices[1] = pLeaf->vertexIndex + pTri->vertIndices[1];
		vertexIndices[2] = pLeaf->vertexIndex + pTri->vertIndices[2];

		assertm(vertexIndices[0] != vertexIndices[1], "we have to parse this now");
	}

	inline const int GetIndice(const int i) const { return vertexIndices[i]; }

private:
	int vertexIndices[3];
};

class IModelPerTriAABBLeaf
{
public:
	IModelPerTriAABBLeaf() = default;
	IModelPerTriAABBLeaf(const r1::mstudiopertrileaf_t* const pLeaf, IModelPerTriAABB* const pPerTriAABB);
	IModelPerTriAABBLeaf(const r1::mstudiopertrileaf_v1_t* const pLeaf, IModelPerTriAABB* const pPerTriAABB);

	inline const int GetTriCount() const { return triangleCount; }
	inline const IModelPerTriAABBTri* const GetTriangle(const int i) const { return &triangles[i]; }

private:
	Vector bbmin;
	Vector bbmax;

	int triangleCount;
	IModelPerTriAABBTri triangles[12];
};

class IModelPerTriAABBNode
{
public:
	IModelPerTriAABBNode() = default;
	IModelPerTriAABBNode(const r1::mstudiopertrinode_t* const pNode, IModelPerTriAABB* const pPerTriAABB);

	inline const bool IsLeaf(const int idx) const { return childIndex[idx] < 0; }

private:
	Vector bbmin;
	Vector bbmax;

	const void* children[2];
	int childIndex[2];
};

class IModelPerTriAABB : public IModelModel
{
public:
	IModelPerTriAABB(const IModel* const imodel, const r1::studiohdr_t* const pHdr, const r1::mstudiopertrihdr_t* const pPerTriHdr);
	IModelPerTriAABB(const IModel* const imodel, const r2::studiohdr_t* const pHdr, const r2::mstudiopertrihdr_t* const pPerTriHdr);
	~IModelPerTriAABB()
	{
		FreeAllocArray(nodes);
		FreeAllocArray(leaves);
		FreeAllocArray(vertices);
	}

	inline const Vector& GetBBMin() const { return bbmin; }
	inline const Vector& GetBBMax() const { return bbmax; }
	inline const Vector& GetScaledVolume() const { return volumeScaled; }
	inline const int GetVersion() const { return version; }

	inline const int GetNodeCount() const { return nodeCount; }
	inline const IModelPerTriAABBNode* const GetNode(const int i) const { return nodes + i; }

	inline const int GetLeafCount() const { return leafCount; }
	inline const IModelPerTriAABBLeaf* const GetLeaf(const int i) const { return leaves + i; }

	inline const int GetVertCount() const { return vertCount; }
	inline const Vector& GetVert(const int i) const { return vertices[i]; }
	inline const int GetTriCount() const { return triangleCount; }

private:
	Vector bbmin;
	Vector bbmax;
	Vector volumeScaled; // volume of bounding boxes scaled by the float
	int version;

	IModelPerTriAABBNode* nodes;
	int nodeCount;

	int leafCount;
	IModelPerTriAABBLeaf* leaves;

	Vector* vertices;
	int vertCount;
	int triangleCount;
};

class IModelUIPanel : public IModelModel
{
public:
	IModelUIPanel() = default;
	IModelUIPanel(const IModel* const imodel, const r2::UIPanelHeader_s* const pUIPanel);
	IModelUIPanel(const IModel* const imodel, const r5::UIPanelHeader_s* const pUIPanel);
	~IModelUIPanel()
	{
		FreeAllocArray(path);
	}

	IModelUIPanel& operator=(const IModelUIPanel&) = delete;
	IModelUIPanel& operator=(IModelUIPanel&& uiPanel) noexcept
	{
		// too lazy to do this proper right now, on a roll
		if (this != &uiPanel)
		{
			memcpy_s(this, sizeof(IModelUIPanel), &uiPanel, sizeof(IModelUIPanel));
			memset(&uiPanel, 0, sizeof(IModelUIPanel));
		}

		return *this;
	}

private:
	char* path;
	int hash;
};


//
// Model Bone Data
//

enum class eProcBoneType : int
{
	NONE = 0,
	AXISINTERP = 1,
	QUATINTERP = 2,
	AIMATBONE = 3,
	AIMATATTACH = 4,
	JIGGLE = 5,
	TWIST_MASTER = 6,
	TWIST_SLAVE = 7,
};

class IModelProcBone
{
public:
	IModelProcBone(const char* name, const uint32_t index, const eProcBoneType type) : boneName(name), boneIndex(index), boneType(type) {}

	inline const char* const GetName() const { return boneName; }
	inline const uint32_t GetIndex() const { return boneIndex; }
	inline const eProcBoneType GetType() const { return boneType; }

private:
	const char* boneName;
	uint32_t boneIndex;
	eProcBoneType boneType;
};

typedef uint16_t IModelJiggleFlags_t;
enum eIModelJiggleFlags : IModelJiggleFlags_t
{
	IMODELJIGGLE_NONE,

	IMODELJIGGLE_IS_FLEXIBLE			= 0x01,
	IMODELJIGGLE_IS_RIGID				= 0x02,
	IMODELJIGGLE_HAS_FLEX				= 0x02,
	IMODELJIGGLE_HAS_YAW_CONSTRAINT		= 0x04,
	IMODELJIGGLE_HAS_PITCH_CONSTRAINT	= 0x08,
	IMODELJIGGLE_HAS_ANGLE_CONSTRAINT	= 0x10,
	IMODELJIGGLE_HAS_LENGTH_CONSTRAINT	= 0x20,
	IMODELJIGGLE_HAS_BASE_SPRING		= 0x40,
	IMODELJIGGLE_IS_BOING				= 0x80,

	IMODELJIGGLE_IS_APEX_LEGENDS	= 0x8000,

	IMODELJIGGLE_FLAG_MASK			= 0xFFFF,
};

class IModelJiggleBone : public IModelProcBone
{
public:
	IModelJiggleBone(const r1::mstudiojigglebone_t* const pJiggle, const char* boneName, const uint32_t boneIndex); // this should just be the p2 one but hard casted since p2/r1/r2 jiggle bones are the same
	IModelJiggleBone(const r2::mstudiojigglebone_t* const pJiggle, const char* boneName, const uint32_t boneIndex);
	IModelJiggleBone(const r5::mstudiojigglebone_t* const pJiggle, const char* boneName);
	~IModelJiggleBone() {}; // shouldn't need to cleanup any

	IModelJiggleFlags_t flags;
	inline const IModelJiggleFlags_t GetFlags() const { return flags; }
	const bool IsApexLegends() const { return (flags & IMODELJIGGLE_IS_APEX_LEGENDS); }

	// general params
	float length; // how far from bone base, along bone, is tip
	float tipMass;
	float tipFriction; // friction applied to tip velocity, 0-1

	// flexible params
	float yawStiffness;
	float yawDamping;
	float pitchStiffness;
	float pitchDamping;
	float alongStiffness;
	float alongDamping;

	// angle constraint
	float angleLimit; // maximum deflection of tip in radians

	// yaw constraint
	float minYaw; // in radians
	float maxYaw; // in radians
	float yawFriction;
	float yawBounce;

	// pitch constraint
	float minPitch; // in radians
	float maxPitch; // in radians
	float pitchFriction;
	float pitchBounce;

	// base spring
	float baseMass;
	float baseStiffness;
	float baseDamping;
	float baseMinLeft;
	float baseMaxLeft;
	float baseLeftFriction;
	float baseMinUp;
	float baseMaxUp;
	float baseUpFriction;
	float baseMinForward;
	float baseMaxForward;
	float baseForwardFriction;
};

class IModelBone
{
public:
	IModelBone() = default;
	IModelBone(const r1::mstudiobone_t* const pBone, const uint32_t indexForProc);
	IModelBone(const r2::mstudiobone_t* const pBone, const uint32_t indexForProc);
	IModelBone(const r5::mstudiobone_t* const pBone);
	~IModelBone();

	IModelBone& operator=(const IModelBone&) = delete;
	IModelBone& operator=(IModelBone&& bone) noexcept
	{
		if (this != &bone)
		{
			memcpy_s(this, sizeof(IModelBone), &bone, sizeof(IModelBone));

			this->name = bone.name;
			this->surfaceProp = bone.surfaceProp;
			this->procBone.generic = bone.procBone.generic;

			bone.name = nullptr;
			bone.surfaceProp = nullptr;
			bone.procBone.generic = nullptr;
		}

		return *this;
	}

	inline const char* GetName() const { return name; }
	inline const char* GetSurfaceProp() const { return surfaceProp; }
	inline const int GetParent() const { return parent; }
	inline const int GetFlags() const { return flags; }
	inline const int GetContents() const { return contents; }

	inline const Vector& GetPos() const { return pos; }
	inline const Quaternion& GetQuat() const { return quat; }
	inline const RadianEuler& GetRot() const { return rot; }
	inline const Vector& GetScale() const { return scale; }

	inline const matrix3x4_t* const GetPoseToBone() const { return &poseToBone; }

	const eProcBoneType GetProcType() const { return procType; }
	template<typename ProcBone> __forceinline ProcBone* const GetProcBone() const { return reinterpret_cast<ProcBone* const>(procBone.generic); }

	inline const uint16_t GetCollIndex() const { return collisionIndex; }
	inline const uint16_t GetCollCount() const { return collisionCount; }

private:
	const char* name;

	int parent; // parent bone

	int flags;
	int contents; // See BSPFlags.h for the contents flags

	// default values
	Vector pos; // base bone position
	Quaternion quat;
	RadianEuler rot; // base bone rotation
	Vector scale; // base bone scale

	matrix3x4_t poseToBone;
	Quaternion qAlignment;

	const char* surfaceProp;
	int surfacepropLookup; // this index must be cached by the loader, not saved in the file

	eProcBoneType procType;

	// still causing issues, I think
	union {
		IModelProcBone* generic; // generic pointer to memory
		IModelJiggleBone* jiggle;
		void* invalid; // replace with other proc bones eventually
	} procBone;

	int physicsbone; // index into physically simulated bone

	// map collision
	uint16_t collisionIndex; // base index into collision shapes, 0xFFFF is no collision
	uint16_t collisionCount; // number of collision shapes for this bone, see: models\s2s\s2s_malta_gun_animated.mdl
};

class IModelBoneTransform
{
public:
	IModelBoneTransform() = default;
	IModelBoneTransform(const r1::mstudiosrcbonetransform_t* const pSrcTransform) : name(AllocStudioString(pSrcTransform->pszName())), pretransform(pSrcTransform->pretransform), posttransform(pSrcTransform->posttransform) {}
	IModelBoneTransform(const r2::mstudiosrcbonetransform_t* const pSrcTransform) : name(AllocStudioString(pSrcTransform->pszName())), pretransform(pSrcTransform->pretransform), posttransform(pSrcTransform->posttransform) {}
	IModelBoneTransform(const r5::mstudiosrcbonetransform_t* const pSrcTransform) : name(AllocStudioString(pSrcTransform->pszName())), pretransform(pSrcTransform->pretransform), posttransform(pSrcTransform->posttransform) {}
	~IModelBoneTransform()
	{
		FreeAllocArray(name);
	}

	IModelBoneTransform& operator=(const IModelBoneTransform&& transform) = delete;
	IModelBoneTransform& operator=(IModelBoneTransform&& transform) noexcept
	{
		if (this != &transform)
		{
			memcpy_s(this, sizeof(IModelBoneTransform), &transform, sizeof(IModelBoneTransform));

			name = transform.name;

			transform.name = nullptr;
		}

		return *this;
	}

	const char* const GetName() const { return name; }
	const matrix3x4_t* const GetPreTransform() const { return &pretransform; }
	const matrix3x4_t* const GetPostTransform() const { return &posttransform; }

	// gets a source bone transform for a bone if it exists
	static const IModelBoneTransform* const GetSrcBoneTransform(const char* const bone, const IModelBoneTransform* const pBoneTransforms, const uint32_t numBoneTransforms)
	{
		const IModelBoneTransform* pBoneTransform = nullptr;

		// [rika]: parse through srcbonetransforms until we find a matching one (by name yikes) or return nullptr if there's no transform for this bone
		for (uint32_t i = 0u; i < numBoneTransforms; i++)
		{
			pBoneTransform = pBoneTransforms + i;

			if (!strncmp(pBoneTransform->GetName(), bone, MAX_PATH))
				return pBoneTransform;
		}

		return nullptr;
	}

private:
	char* name;

	matrix3x4_t	pretransform;
	matrix3x4_t	posttransform;
};

class IModelHitbox
{
public:
	IModelHitbox() = default;
	IModelHitbox(const r1::mstudiobbox_t* const pBBox);
	IModelHitbox(const r2::mstudiobbox_t* const pBBox);
	IModelHitbox(const r5::mstudiobbox_t* const pBBox);
	~IModelHitbox()
	{
		FreeAllocArray(hitboxName);
		FreeAllocArray(hitdataGroup);
	}

	inline const int GetBone() const { return bone; }
	inline const int GetGroup() const { return group; }
	inline const Vector* const GetBBMin() const { return &bbmin; }
	inline const Vector* const GetBBMax() const { return &bbmax; }

	inline const char* const GetHitboxName() const
	{
		if (hitboxName == nullptr)
			return "";

		return hitboxName;
	}

	inline const char* const GetHitDataGroup() const
	{
		if (hitdataGroup == nullptr)
			return "";

		return hitdataGroup;
	}

	inline const int GetForceCritPoint() const { return forceCritPoint; }

	IModelHitbox& operator=(const IModelHitbox&& hitbox) = delete;
	IModelHitbox& operator=(IModelHitbox&& hitbox) noexcept
	{
		if (this != &hitbox)
		{
			memcpy_s(this, sizeof(IModelHitbox), &hitbox, sizeof(IModelHitbox));

			hitboxName = hitbox.hitboxName;
			hitdataGroup = hitbox.hitdataGroup;

			hitbox.hitboxName = nullptr;
			hitbox.hitdataGroup = nullptr;
		}

		return *this;
	}

private:
	int bone;
	int group;				// intersection group
	Vector bbmin;			// bounding box
	Vector bbmax;

	char* hitboxName;	// offset to the name of the hitbox.

	int forceCritPoint;	// value of one causes this to act as if it was group of 'head', may either be crit override or group override. mayhaps aligned boolean, look into this
	char* hitdataGroup;	// hit_data group in keyvalues this hitbox uses.
};

class IModelHitboxSet
{
public:
	IModelHitboxSet() = default;
	IModelHitboxSet(const r1::mstudiohitboxset_t* const pHitboxSet) : name(nullptr), hitboxes(nullptr), hitboxCount(static_cast<uint32_t>(pHitboxSet->numhitboxes))
	{
		name = AllocStudioString(pHitboxSet->pszName());

		if (pHitboxSet->numhitboxes)
		{
			hitboxes = new IModelHitbox[pHitboxSet->numhitboxes]{};

			for (int i = 0; i < pHitboxSet->numhitboxes; i++)
			{
				hitboxes[i] = IModelHitbox(pHitboxSet->pHitbox(i));
			}
		}
	}
	IModelHitboxSet(const r2::mstudiohitboxset_t* const pHitboxSet) : name(nullptr), hitboxes(nullptr), hitboxCount(static_cast<uint32_t>(pHitboxSet->numhitboxes))
	{
		name = AllocStudioString(pHitboxSet->pszName());

		if (pHitboxSet->numhitboxes)
		{
			hitboxes = new IModelHitbox[pHitboxSet->numhitboxes]{};

			for (int i = 0; i < pHitboxSet->numhitboxes; i++)
			{
				hitboxes[i] = IModelHitbox(pHitboxSet->pHitbox(i));
			}
		}
	}
	IModelHitboxSet(const r5::mstudiohitboxset_t* const pHitboxSet) : name(nullptr), hitboxes(nullptr), hitboxCount(static_cast<uint32_t>(pHitboxSet->numhitboxes))
	{
		name = AllocStudioString(pHitboxSet->pszName());

		if (pHitboxSet->numhitboxes)
		{
			hitboxes = new IModelHitbox[pHitboxSet->numhitboxes]{};

			for (int i = 0; i < pHitboxSet->numhitboxes; i++)
			{
				hitboxes[i] = IModelHitbox(pHitboxSet->pHitbox(i));
			}
		}
	}

	~IModelHitboxSet()
	{
		FreeAllocArray(name);
		FreeAllocArray(hitboxes);
	}

	inline const char* const GetName() const { return name; }
	inline const IModelHitbox* const GetHitbox(const uint32_t index) const { return hitboxes + index; }
	inline const uint32_t GetHitboxCount() const { return hitboxCount; }

	IModelHitboxSet& operator=(const IModelHitboxSet&& hitboxset) = delete;
	IModelHitboxSet& operator=(IModelHitboxSet&& hitboxset) noexcept
	{
		if (this != &hitboxset)
		{
			name = hitboxset.name;
			hitboxes = hitboxset.hitboxes;
			hitboxCount = hitboxset.hitboxCount;

			hitboxset.name = nullptr;
			hitboxset.hitboxes = nullptr;
		}

		return *this;
	}

private:
	char* name;

	IModelHitbox* hitboxes;
	uint32_t hitboxCount;
};

class IModelAttachment
{
public:
	IModelAttachment() = default;
	IModelAttachment(const r1::mstudioattachment_t* const pAttachment) : name(AllocStudioString(pAttachment->pszName())), flags(pAttachment->flags), localbone(pAttachment->localbone), local(pAttachment->local) {}
	IModelAttachment(const r2::mstudioattachment_t* const pAttachment) : name(AllocStudioString(pAttachment->pszName())), flags(pAttachment->flags), localbone(pAttachment->localbone), local(pAttachment->local) {}
	IModelAttachment(const r5::mstudioattachment_t* const pAttachment) : name(AllocStudioString(pAttachment->pszName())), flags(pAttachment->flags), localbone(pAttachment->localbone), local(pAttachment->localmatrix) {}
	~IModelAttachment()
	{
		FreeAllocArray(name);
	}

	inline const char* const GetName() const { return name; }
	inline const uint32_t GetFlags() const { return flags; }
	inline const uint32_t GetLocalBone() const { return localbone; }
	inline const matrix3x4_t* const GetLocal() const { return &local; }

	IModelAttachment& operator=(const IModelAttachment&&) = delete;
	IModelAttachment& operator=(IModelAttachment&& attachment) noexcept
	{
		if (this != &attachment)
		{
			memcpy_s(this, sizeof(IModelAttachment), &attachment, sizeof(IModelAttachment));

			name = attachment.name;
			attachment.name = nullptr;
		}

		return *this;
	}
	
private:
	char* name;
	uint32_t flags;
	uint32_t localbone;
	matrix3x4_t local; // attachment point
};


//
// IModel
//

#define IMODEL_ALLOC_DATA(type, ptr, count, num)			\
{															\
	assertm(ptr == nullptr, "data was already allocated");	\
															\
	count = num;											\
	if (count > 0)											\
	{														\
		ptr = new type[count]{};							\
	}														\
}

#define IMODEL_ALLOC_DATA_LIMIT(type, ptr, count, num, limit)	\
{																\
	assertm(limit >= num, "data count exceeded limit");			\
	IMODEL_ALLOC_DATA(type, ptr, count, num);					\
}

class IModel
{
public:
	
	IModel(const std::filesystem::path path, const r1::studiohdr_t* const pHdr);
	IModel(const std::filesystem::path path, const r2::studiohdr_t* const pHdr);
	IModel(const std::filesystem::path path, const r5::studiohdr_t* const pHdr, const IModelSourceVersion_t version);
	~IModel();

	// returns allocated memory
	static IModel* const LoadStudioModel(const std::filesystem::path path);

	// source data
	std::filesystem::path sourcePath; // path to the original file
	IModelSource_t source;
	IModelSourceFlags_t sourceFlags; // eIModelFlags (should match studio hdr flags)
	IModelSourceType_t sourceType;
	inline const IModelSourceFlags_t GetFlags() const { return sourceFlags; }

	// studio data
	char namedebug[64]; // The internal name of the model, padding with null chars. this can differ from the szName
	const char* name;
	inline const char* GetName() const { return name; }

	Vector eyeposition;		// ideal eye position
	Vector illumposition;	// illumination center
	const Vector* const GetEyePos() const { return &eyeposition; }
	const Vector* const GetIllumPos() const { return &illumposition; }

	Vector hull_min;	// ideal movement hull size
	Vector hull_max;	// ideal movement hull size
	inline const Vector* const GetHullMin() const { return &hull_min; }
	inline const Vector* const GetHullMax() const { return &hull_max; }

	Vector view_bbmin;	// clipping bounding box
	Vector view_bbmax;	// clipping bounding box
	inline const Vector* const GetBBMin() const { return &view_bbmin; }
	inline const Vector* const GetBBMax() const { return &view_bbmax; }

	IModelBone* bones;
	uint32_t boneCount;
	inline const IModelBone* const GetBone(const uint32_t index) const { return bones + index; }
	inline const uint32_t GetBoneCount() const { return boneCount; }
	const uint32_t GetBoneIndex(const char* const bone) const
	{
		const size_t nameLength = strnlen_s(bone, MAX_PATH_SOURCE);

		uint32_t index = 0;
		for (index = 0; index < boneCount; index++)
		{
			const int success = strncmp(bones[index].GetName(), bone, nameLength);
			if (success == 0)
				break;
		}

		if (index == boneCount)
			return UINT_MAX;

		return index;
	}
	std::vector<uint32_t> GetBoneChildren(const uint32_t bone) const;

	uint32_t hitboxSetCount;
	IModelHitboxSet* hitboxSets;
	inline const IModelHitboxSet* const GetHitboxSet(const uint32_t index) const { return hitboxSets + index; }
	inline const uint32_t GetHitboxSetCount() const { return hitboxSetCount; }

	IModelAnimation* animations;
	uint32_t animationCount;
	inline const IModelAnimation* const GetAnimation(const uint32_t index) const { return animationCount > index ? animations + index : nullptr; }
	inline const uint32_t GetAnimationCount() const { return animationCount; }

	uint32_t sequenceCount;
	IModelSequence* sequences;
	inline const IModelSequence* const GetSequence(const uint32_t index) const { return sequences + index; }
	inline const uint32_t GetSequenceCount() const { return sequenceCount; }

	IModelTexture* textures;
	uint32_t textureCount;
	inline const uint32_t GetMaterialCount() const { return textureCount; }
	const IModelTexture* const GetMaterial(const int index) const
	{
		if (index > eIModelTextureType::IMODELTEXTURE_INVALID)
		{
			return textures + index;
		}

		switch (index)
		{
		case eIModelTextureType::IMODELTEXTURE_UIPANEL:
		{
			return &s_TextureUIPanel;
		}
		case eIModelTextureType::IMODELTEXTURE_PHYSICS:
		{
			return &s_TexturePhysics;
		}
		case eIModelTextureType::IMODELTEXTURE_INVALID:
		default:
		{
			assertm(false, "invalid material index");
			return nullptr;
		}
		}
	}

	uint32_t cdTexturesCount;
	char** cdTextures;
	inline const uint32_t GetCDTextureCount() const { return cdTexturesCount; }
	inline const char* const GetCDTexture(const uint32_t index) const { return cdTextures[index]; }

	IModelSkin* skins;
	uint32_t skinCount;
	inline const uint32_t GetSkinCount() const { return skinCount; }
	inline const IModelSkin* const GetSkin(const uint32_t index) const { return skins + index; }

	uint32_t bodypartCount;
	IModelBodypart* bodyparts;
	inline const IModelBodypart* const GetBodyPart(const uint32_t index) const { return bodyparts + index; }
	inline const uint32_t GetBodyPartCount() const { return bodypartCount; }

	IModelAttachment* localAttachments;
	uint32_t localAttachmentCount;
	inline const IModelAttachment* const GetAttachment(const uint32_t index) const { return localAttachments + index; }
	inline const uint32_t GetAttachmentCount() const { return localAttachmentCount; }

	// todo transitions
	uint32_t localNodeCount;
	char** localNodeNames;
	inline const char* const GetNodeName(const uint32_t index) const { return localNodeNames[index]; }
	inline const uint32_t GetNodeCount() const { return localNodeCount; }

	IModelIKChain* ikChains;
	uint32_t ikChainCount;
	inline const IModelIKChain* const GetIKChain(const uint32_t index) const { return ikChains + index; }
	inline const uint32_t GetIKChainCount() const { return ikChainCount; }

	uint32_t uiPanelCount;
	IModelUIPanel* uiPanels; // note here mirror the tris!	
	inline const IModelUIPanel* const GetUIPanel(const uint32_t index) const { return uiPanels + index; }
	inline const uint32_t GetUIPanelCount() const { return uiPanelCount; }

	IModelPoseParameter* localPoseParameters;
	uint32_t localPoseParameterCount;
	inline const IModelPoseParameter* const GetPoseParameter(const uint32_t index) const { return localPoseParameters + index; }
	inline const uint32_t GetPoseParameterCount() const { return localPoseParameterCount; }

	char* surfaceProp;
	inline const char* const GetSurfaceProp() const { return surfaceProp; }

	char* keyValues;
	inline const char* const KeyValueText() const { return keyValues; }
	
	IModelIKLock* localIkAutoPlayLocks;
	uint32_t localIkAutoPlayLockCount;
	inline const IModelIKLock* const GetIKLock(const uint32_t index) const { return localIkAutoPlayLocks + index; }
	inline const uint32_t GetIKLockCount() const { return localIkAutoPlayLockCount; }

	float mass;
	int contents;	// contents mask, see bspflags.h
	inline const int GetContents() const { return contents; }

	uint32_t includeModelCount;
	IModelModelGroup* includeModels;
	inline const IModelModelGroup* const GetModelGroup(const uint32_t index) const { return includeModels + index; }
	inline const uint32_t GetModelGroupCount() const { return includeModelCount; }

	char* animBlockName;
	IModelAnimBlock* animBlocks;
	uint32_t animBlockCount;
	inline const char* const GetAnimBlockName() const { return animBlockName; }
	inline const IModelAnimBlock* const GetAnimBlock(const uint32_t index) const { return animBlocks + index; }
	inline const uint32_t GetAnimBlockCount() const { return animBlockCount; }

	uint8_t constdirectionallightdot;
	uint8_t rootLOD;
	uint8_t numAllowedRootLODs;
	inline const uint8_t GetConstDirectionalLightDot() const { return constdirectionallightdot; }
	inline const uint8_t GetRootLOD() const { return rootLOD; }
	inline const uint8_t GetNumAllowedRootLOD() const { return numAllowedRootLODs; }

	float fadeDistance; // set to -1 to never fade. set above 0 if you want it to fade out, distance is in feet.
	float gatherSize;
	inline const float GetFadeDistance() const { return fadeDistance; }

	int	illumpositionattachmentindex;
	inline const int GetIllumPosAttachmentIndex() const { return illumpositionattachmentindex; }

	float flMaxEyeDeflection;
	const float GetMaxEyeDeflection() const { return flMaxEyeDeflection; }

	IModelBoneTransform* boneTransforms;
	uint32_t boneTransformCount;
	inline const uint32_t GetBoneTransformCount() const { return boneTransformCount; }
	inline const IModelBoneTransform* const GetBoneTransform(const uint32_t index) const { return boneTransforms + index; }

	uint32_t procBoneCount;
	IModelProcBone** procBones;

	int* boneFollowers;
	uint32_t boneFollowerCount;

	uint32_t lodCount;
	IModelLOD* lods;
	inline const IModelLOD* const GetLOD(const uint32_t index) const { return lods + index; }
	inline const uint32_t GetLODCount() const { return lodCount; }

	IModelPhysics* physics;
	const IModelPhysics* const GetPhysics() const { return physics; }

	IModelMapCollision* mapCollision;
	const IModelMapCollision* const GetMapColl() const { return mapCollision; }

	IModelPerTriAABB* perTriAABB;
	const IModelPerTriAABB* const GetPerTriAABB() const { return perTriAABB; }

private:
	inline void SetFlags_R1(const int flags)
	{
		// should not have: STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS, STUDIOHDR_FLAGS_OBSOLETE, STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT, or STUDIOHDR_FLAGS_FLEXES_CONVERTED
		// STUDIOHDR_FLAGS_UNUSED_8 (STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS) set on models, but does not function in code. legacy studiomdl data?
		constexpr int maskDisabledFlags = (STUDIOHDR_FLAGS_UNUSED_2000 | STUDIOHDR_FLAGS_UNUSED_4000);
		assertm((flags & maskDisabledFlags) == false, "studio model had unused flag");

		sourceFlags = IMODELFLAGS_NONE;
		sourceFlags |= (flags & ~maskDisabledFlags);

		// no flags to adjust
	}

	inline void SetFlags_R2(const int flags)
	{
		// should not have: STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS, STUDIOHDR_FLAGS_OBSOLETE, STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT, or STUDIOHDR_FLAGS_FLEXES_CONVERTED
		constexpr int maskDisabledFlags = (STUDIOHDR_FLAGS_UNUSED_8 | STUDIOHDR_FLAGS_UNUSED_200 | STUDIOHDR_FLAGS_UNUSED_2000 | STUDIOHDR_FLAGS_UNUSED_4000);
		assertm((flags & maskDisabledFlags) == false, "studio model had unused flag");

		sourceFlags = IMODELFLAGS_NONE;
		sourceFlags |= (flags & ~maskDisabledFlags);

		// no flags to adjust
	}

	inline void SetFlags_R5(const int flags)
	{
		// flags previously known as: STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS, STUDIOHDR_FLAGS_OBSOLETE, STUDIOHDR_FLAGS_UNUSED, STUDIOHDR_FLAGS_CONSTANT_DIRECTIONAL_LIGHT_DOT, and STUDIOHDR_FLAGS_FLEXES_CONVERTED
		constexpr int maskDisabledFlags = (STUDIOHDR_FLAGS_UNK_8 | STUDIOHDR_FLAGS_UNUSED_200 | STUDIOHDR_FLAGS_UNK_400 | STUDIOHDR_FLAGS_UNK_2000 | STUDIOHDR_FLAGS_USES_EXTRA_BONE_WEIGHTS);

		sourceFlags = IMODELFLAGS_NONE;
		sourceFlags |= (flags & ~maskDisabledFlags);

		if (flags & STUDIOHDR_FLAGS_USES_EXTRA_BONE_WEIGHTS)
		{
			sourceFlags |= eIModelFlags::IMODEL_FLAG_USES_EXTRA_BONE_WEIGHTS;
		}

		if (flags & STUDIOHDR_FLAGS_UNK_8)
		{
			sourceFlags |= eIModelFlags::IMODEL_FLAG_UNK_8;
		}

		if (flags & STUDIOHDR_FLAGS_UNK_400)
		{
			sourceFlags |= eIModelFlags::IMODEL_FLAG_UNK_400;
		}

		if (flags & STUDIOHDR_FLAGS_UNK_2000)
		{
			sourceFlags |= eIModelFlags::IMODEL_FLAG_UNK_2000;
		}
	}
};

//
// Utils Functions
// 

// name adjustment
constexpr size_t maxModelNameSize = 64ull;
constexpr size_t maxLODNameSize = maxModelNameSize + 16;
constexpr const char* const lodNameFmt = "%s_%s%u";

const char* const IModel_ParseLodName(const char* const source, const uint32_t lod, const bool hasLODs);
const char* const IModel_ParseClampedName(const char* const bodypartName, const IModelLOD* const lod, const uint32_t lodModelIndex);
const char* const IModel_ParseModelName(const char* const source, const char* const model, const char* const bodypartName, const bool hasValidNames, const IModelLOD* const lod, const uint32_t lodModelIndex, const bool hasLODs);